/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing CallPriceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallPriceResponseTests
    {
        // TODO uncomment below to declare an instance variable for CallPriceResponse
        //private CallPriceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallPriceResponse
            //instance = new CallPriceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallPriceResponse
        /// </summary>
        [Test]
        public void CallPriceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallPriceResponse
            //Assert.IsInstanceOfType<CallPriceResponse> (instance, "variable 'instance' is a CallPriceResponse");
        }


        /// <summary>
        /// Test the property 'Outbound'
        /// </summary>
        [Test]
        public void OutboundTest()
        {
            // TODO unit test for the property 'Outbound'
        }
        /// <summary>
        /// Test the property 'Inbound'
        /// </summary>
        [Test]
        public void InboundTest()
        {
            // TODO unit test for the property 'Inbound'
        }
        /// <summary>
        /// Test the property 'Forward'
        /// </summary>
        [Test]
        public void ForwardTest()
        {
            // TODO unit test for the property 'Forward'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
