/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing Chat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChatTests
    {
        // TODO uncomment below to declare an instance variable for Chat
        //private Chat instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Chat
            //instance = new Chat();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Chat
        /// </summary>
        [Test]
        public void ChatInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Chat
            //Assert.IsInstanceOfType<Chat> (instance, "variable 'instance' is a Chat");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OriginalId'
        /// </summary>
        [Test]
        public void OriginalIdTest()
        {
            // TODO unit test for the property 'OriginalId'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'UnsubscribedContactId'
        /// </summary>
        [Test]
        public void UnsubscribedContactIdTest()
        {
            // TODO unit test for the property 'UnsubscribedContactId'
        }
        /// <summary>
        /// Test the property 'Unread'
        /// </summary>
        [Test]
        public void UnreadTest()
        {
            // TODO unit test for the property 'Unread'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Mute'
        /// </summary>
        [Test]
        public void MuteTest()
        {
            // TODO unit test for the property 'Mute'
        }
        /// <summary>
        /// Test the property 'LastMessage'
        /// </summary>
        [Test]
        public void LastMessageTest()
        {
            // TODO unit test for the property 'LastMessage'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Test]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'MutedUntil'
        /// </summary>
        [Test]
        public void MutedUntilTest()
        {
            // TODO unit test for the property 'MutedUntil'
        }
        /// <summary>
        /// Test the property 'TimeLeftMute'
        /// </summary>
        [Test]
        public void TimeLeftMuteTest()
        {
            // TODO unit test for the property 'TimeLeftMute'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Pinned'
        /// </summary>
        [Test]
        public void PinnedTest()
        {
            // TODO unit test for the property 'Pinned'
        }

    }

}
