/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing CreateListInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateListInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for CreateListInputObject
        //private CreateListInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateListInputObject
            //instance = new CreateListInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateListInputObject
        /// </summary>
        [Test]
        public void CreateListInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateListInputObject
            //Assert.IsInstanceOfType<CreateListInputObject> (instance, "variable 'instance' is a CreateListInputObject");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Test]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'Favorited'
        /// </summary>
        [Test]
        public void FavoritedTest()
        {
            // TODO unit test for the property 'Favorited'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Test]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }

    }

}
