/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing CreateEmailCampaignResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateEmailCampaignResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateEmailCampaignResponse
        //private CreateEmailCampaignResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateEmailCampaignResponse
            //instance = new CreateEmailCampaignResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateEmailCampaignResponse
        /// </summary>
        [Test]
        public void CreateEmailCampaignResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateEmailCampaignResponse
            //Assert.IsInstanceOfType<CreateEmailCampaignResponse> (instance, "variable 'instance' is a CreateEmailCampaignResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'EmailSenderId'
        /// </summary>
        [Test]
        public void EmailSenderIdTest()
        {
            // TODO unit test for the property 'EmailSenderId'
        }
        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Test]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'FromName'
        /// </summary>
        [Test]
        public void FromNameTest()
        {
            // TODO unit test for the property 'FromName'
        }
        /// <summary>
        /// Test the property 'FromEmail'
        /// </summary>
        [Test]
        public void FromEmailTest()
        {
            // TODO unit test for the property 'FromEmail'
        }
        /// <summary>
        /// Test the property 'ReplyToEmail'
        /// </summary>
        [Test]
        public void ReplyToEmailTest()
        {
            // TODO unit test for the property 'ReplyToEmail'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Html'
        /// </summary>
        [Test]
        public void HtmlTest()
        {
            // TODO unit test for the property 'Html'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }
        /// <summary>
        /// Test the property 'Totals'
        /// </summary>
        [Test]
        public void TotalsTest()
        {
            // TODO unit test for the property 'Totals'
        }
        /// <summary>
        /// Test the property 'OutboundEmail'
        /// </summary>
        [Test]
        public void OutboundEmailTest()
        {
            // TODO unit test for the property 'OutboundEmail'
        }
        /// <summary>
        /// Test the property 'FailedReason'
        /// </summary>
        [Test]
        public void FailedReasonTest()
        {
            // TODO unit test for the property 'FailedReason'
        }

    }

}
