/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing DoEmailLookupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoEmailLookupResponseTests
    {
        // TODO uncomment below to declare an instance variable for DoEmailLookupResponse
        //private DoEmailLookupResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoEmailLookupResponse
            //instance = new DoEmailLookupResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoEmailLookupResponse
        /// </summary>
        [Test]
        public void DoEmailLookupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoEmailLookupResponse
            //Assert.IsInstanceOfType<DoEmailLookupResponse> (instance, "variable 'instance' is a DoEmailLookupResponse");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Deliverability'
        /// </summary>
        [Test]
        public void DeliverabilityTest()
        {
            // TODO unit test for the property 'Deliverability'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Risk'
        /// </summary>
        [Test]
        public void RiskTest()
        {
            // TODO unit test for the property 'Risk'
        }
        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Test]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }
        /// <summary>
        /// Test the property 'IsDisposableAddress'
        /// </summary>
        [Test]
        public void IsDisposableAddressTest()
        {
            // TODO unit test for the property 'IsDisposableAddress'
        }
        /// <summary>
        /// Test the property 'Suggestion'
        /// </summary>
        [Test]
        public void SuggestionTest()
        {
            // TODO unit test for the property 'Suggestion'
        }
        /// <summary>
        /// Test the property 'EmailRole'
        /// </summary>
        [Test]
        public void EmailRoleTest()
        {
            // TODO unit test for the property 'EmailRole'
        }
        /// <summary>
        /// Test the property 'LocalPart'
        /// </summary>
        [Test]
        public void LocalPartTest()
        {
            // TODO unit test for the property 'LocalPart'
        }
        /// <summary>
        /// Test the property 'DomainPart'
        /// </summary>
        [Test]
        public void DomainPartTest()
        {
            // TODO unit test for the property 'DomainPart'
        }
        /// <summary>
        /// Test the property 'Exchange'
        /// </summary>
        [Test]
        public void ExchangeTest()
        {
            // TODO unit test for the property 'Exchange'
        }
        /// <summary>
        /// Test the property 'Preference'
        /// </summary>
        [Test]
        public void PreferenceTest()
        {
            // TODO unit test for the property 'Preference'
        }
        /// <summary>
        /// Test the property 'IsInWhiteList'
        /// </summary>
        [Test]
        public void IsInWhiteListTest()
        {
            // TODO unit test for the property 'IsInWhiteList'
        }
        /// <summary>
        /// Test the property 'IsInBlackList'
        /// </summary>
        [Test]
        public void IsInBlackListTest()
        {
            // TODO unit test for the property 'IsInBlackList'
        }
        /// <summary>
        /// Test the property 'HasMx'
        /// </summary>
        [Test]
        public void HasMxTest()
        {
            // TODO unit test for the property 'HasMx'
        }
        /// <summary>
        /// Test the property 'HasAa'
        /// </summary>
        [Test]
        public void HasAaTest()
        {
            // TODO unit test for the property 'HasAa'
        }
        /// <summary>
        /// Test the property 'HasAaaa'
        /// </summary>
        [Test]
        public void HasAaaaTest()
        {
            // TODO unit test for the property 'HasAaaa'
        }

    }

}
