/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing FavoriteContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FavoriteContactTests
    {
        // TODO uncomment below to declare an instance variable for FavoriteContact
        //private FavoriteContact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FavoriteContact
            //instance = new FavoriteContact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FavoriteContact
        /// </summary>
        [Test]
        public void FavoriteContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FavoriteContact
            //Assert.IsInstanceOfType<FavoriteContact> (instance, "variable 'instance' is a FavoriteContact");
        }


        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Test]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'PrimaryLabel'
        /// </summary>
        [Test]
        public void PrimaryLabelTest()
        {
            // TODO unit test for the property 'PrimaryLabel'
        }
        /// <summary>
        /// Test the property 'SecondaryLabel'
        /// </summary>
        [Test]
        public void SecondaryLabelTest()
        {
            // TODO unit test for the property 'SecondaryLabel'
        }
        /// <summary>
        /// Test the property 'TertiaryLabel'
        /// </summary>
        [Test]
        public void TertiaryLabelTest()
        {
            // TODO unit test for the property 'TertiaryLabel'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Test]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }

    }

}
