/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetAllScheduledMessagesPaginatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAllScheduledMessagesPaginatedResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAllScheduledMessagesPaginatedResponse
        //private GetAllScheduledMessagesPaginatedResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAllScheduledMessagesPaginatedResponse
            //instance = new GetAllScheduledMessagesPaginatedResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAllScheduledMessagesPaginatedResponse
        /// </summary>
        [Test]
        public void GetAllScheduledMessagesPaginatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAllScheduledMessagesPaginatedResponse
            //Assert.IsInstanceOfType<GetAllScheduledMessagesPaginatedResponse> (instance, "variable 'instance' is a GetAllScheduledMessagesPaginatedResponse");
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Test]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

    }

}
