/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetAvailableDedicatedNumbersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAvailableDedicatedNumbersResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAvailableDedicatedNumbersResponse
        //private GetAvailableDedicatedNumbersResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAvailableDedicatedNumbersResponse
            //instance = new GetAvailableDedicatedNumbersResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAvailableDedicatedNumbersResponse
        /// </summary>
        [Test]
        public void GetAvailableDedicatedNumbersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAvailableDedicatedNumbersResponse
            //Assert.IsInstanceOfType<GetAvailableDedicatedNumbersResponse> (instance, "variable 'instance' is a GetAvailableDedicatedNumbersResponse");
        }


        /// <summary>
        /// Test the property 'Numbers'
        /// </summary>
        [Test]
        public void NumbersTest()
        {
            // TODO unit test for the property 'Numbers'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
