/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetCallbackSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetCallbackSettingsResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetCallbackSettingsResponse
        //private GetCallbackSettingsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCallbackSettingsResponse
            //instance = new GetCallbackSettingsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCallbackSettingsResponse
        /// </summary>
        [Test]
        public void GetCallbackSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetCallbackSettingsResponse
            //Assert.IsInstanceOfType<GetCallbackSettingsResponse> (instance, "variable 'instance' is a GetCallbackSettingsResponse");
        }


        /// <summary>
        /// Test the property 'OutUrl'
        /// </summary>
        [Test]
        public void OutUrlTest()
        {
            // TODO unit test for the property 'OutUrl'
        }
        /// <summary>
        /// Test the property 'InUrl'
        /// </summary>
        [Test]
        public void InUrlTest()
        {
            // TODO unit test for the property 'InUrl'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

    }

}
