/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetMessagePreviewResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetMessagePreviewResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetMessagePreviewResponse
        //private GetMessagePreviewResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetMessagePreviewResponse
            //instance = new GetMessagePreviewResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetMessagePreviewResponse
        /// </summary>
        [Test]
        public void GetMessagePreviewResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetMessagePreviewResponse
            //Assert.IsInstanceOfType<GetMessagePreviewResponse> (instance, "variable 'instance' is a GetMessagePreviewResponse");
        }


        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

    }

}
