/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing GetMessagePriceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetMessagePriceResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetMessagePriceResponse
        //private GetMessagePriceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetMessagePriceResponse
            //instance = new GetMessagePriceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetMessagePriceResponse
        /// </summary>
        [Test]
        public void GetMessagePriceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetMessagePriceResponse
            //Assert.IsInstanceOfType<GetMessagePriceResponse> (instance, "variable 'instance' is a GetMessagePriceResponse");
        }


        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Parts'
        /// </summary>
        [Test]
        public void PartsTest()
        {
            // TODO unit test for the property 'Parts'
        }
        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Test]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }

    }

}
