/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing MarkChatsUnreadBulkInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarkChatsUnreadBulkInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for MarkChatsUnreadBulkInputObject
        //private MarkChatsUnreadBulkInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarkChatsUnreadBulkInputObject
            //instance = new MarkChatsUnreadBulkInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarkChatsUnreadBulkInputObject
        /// </summary>
        [Test]
        public void MarkChatsUnreadBulkInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarkChatsUnreadBulkInputObject
            //Assert.IsInstanceOfType<MarkChatsUnreadBulkInputObject> (instance, "variable 'instance' is a MarkChatsUnreadBulkInputObject");
        }


        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Test]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }

    }

}
