/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing ScheduleEmailCampaignResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ScheduleEmailCampaignResponseTests
    {
        // TODO uncomment below to declare an instance variable for ScheduleEmailCampaignResponse
        //private ScheduleEmailCampaignResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ScheduleEmailCampaignResponse
            //instance = new ScheduleEmailCampaignResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ScheduleEmailCampaignResponse
        /// </summary>
        [Test]
        public void ScheduleEmailCampaignResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScheduleEmailCampaignResponse
            //Assert.IsInstanceOfType<ScheduleEmailCampaignResponse> (instance, "variable 'instance' is a ScheduleEmailCampaignResponse");
        }


        /// <summary>
        /// Test the property 'Campaign'
        /// </summary>
        [Test]
        public void CampaignTest()
        {
            // TODO unit test for the property 'Campaign'
        }
        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Test]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }

    }

}
