/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing Timezone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TimezoneTests
    {
        // TODO uncomment below to declare an instance variable for Timezone
        //private Timezone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Timezone
            //instance = new Timezone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Timezone
        /// </summary>
        [Test]
        public void TimezoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Timezone
            //Assert.IsInstanceOfType<Timezone> (instance, "variable 'instance' is a Timezone");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Test]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }
        /// <summary>
        /// Test the property 'Dst'
        /// </summary>
        [Test]
        public void DstTest()
        {
            // TODO unit test for the property 'Dst'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property '_Timezone'
        /// </summary>
        [Test]
        public void _TimezoneTest()
        {
            // TODO unit test for the property '_Timezone'
        }

    }

}
