/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing UpdateContactInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateContactInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for UpdateContactInputObject
        //private UpdateContactInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateContactInputObject
            //instance = new UpdateContactInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateContactInputObject
        /// </summary>
        [Test]
        public void UpdateContactInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateContactInputObject
            //Assert.IsInstanceOfType<UpdateContactInputObject> (instance, "variable 'instance' is a UpdateContactInputObject");
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'Lists'
        /// </summary>
        [Test]
        public void ListsTest()
        {
            // TODO unit test for the property 'Lists'
        }
        /// <summary>
        /// Test the property 'Favorited'
        /// </summary>
        [Test]
        public void FavoritedTest()
        {
            // TODO unit test for the property 'Favorited'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Test]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CustomFieldValues'
        /// </summary>
        [Test]
        public void CustomFieldValuesTest()
        {
            // TODO unit test for the property 'CustomFieldValues'
        }
        /// <summary>
        /// Test the property 'Local'
        /// </summary>
        [Test]
        public void LocalTest()
        {
            // TODO unit test for the property 'Local'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

    }

}
