/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing UpdateBalanceNotificationSettingsInputObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateBalanceNotificationSettingsInputObjectTests
    {
        // TODO uncomment below to declare an instance variable for UpdateBalanceNotificationSettingsInputObject
        //private UpdateBalanceNotificationSettingsInputObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateBalanceNotificationSettingsInputObject
            //instance = new UpdateBalanceNotificationSettingsInputObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateBalanceNotificationSettingsInputObject
        /// </summary>
        [Test]
        public void UpdateBalanceNotificationSettingsInputObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateBalanceNotificationSettingsInputObject
            //Assert.IsInstanceOfType<UpdateBalanceNotificationSettingsInputObject> (instance, "variable 'instance' is a UpdateBalanceNotificationSettingsInputObject");
        }


        /// <summary>
        /// Test the property 'LowBalanceNotification'
        /// </summary>
        [Test]
        public void LowBalanceNotificationTest()
        {
            // TODO unit test for the property 'LowBalanceNotification'
        }
        /// <summary>
        /// Test the property 'AlertBalance'
        /// </summary>
        [Test]
        public void AlertBalanceTest()
        {
            // TODO unit test for the property 'AlertBalance'
        }
        /// <summary>
        /// Test the property 'AlertPhone'
        /// </summary>
        [Test]
        public void AlertPhoneTest()
        {
            // TODO unit test for the property 'AlertPhone'
        }
        /// <summary>
        /// Test the property 'AlertEmail1'
        /// </summary>
        [Test]
        public void AlertEmail1Test()
        {
            // TODO unit test for the property 'AlertEmail1'
        }
        /// <summary>
        /// Test the property 'AlertEmail2'
        /// </summary>
        [Test]
        public void AlertEmail2Test()
        {
            // TODO unit test for the property 'AlertEmail2'
        }
        /// <summary>
        /// Test the property 'AlertEmail3'
        /// </summary>
        [Test]
        public void AlertEmail3Test()
        {
            // TODO unit test for the property 'AlertEmail3'
        }

    }

}
