/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TextMagicClient.Api;
using TextMagicClient.Model;
using TextMagicClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TextMagicClient.Test
{
    /// <summary>
    ///  Class for testing UsersInbound
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UsersInboundTests
    {
        // TODO uncomment below to declare an instance variable for UsersInbound
        //private UsersInbound instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UsersInbound
            //instance = new UsersInbound();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UsersInbound
        /// </summary>
        [Test]
        public void UsersInboundInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UsersInbound
            //Assert.IsInstanceOfType<UsersInbound> (instance, "variable 'instance' is a UsersInbound");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayTimeFormat'
        /// </summary>
        [Test]
        public void DisplayTimeFormatTest()
        {
            // TODO unit test for the property 'DisplayTimeFormat'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'PurchasedAt'
        /// </summary>
        [Test]
        public void PurchasedAtTest()
        {
            // TODO unit test for the property 'PurchasedAt'
        }
        /// <summary>
        /// Test the property 'ExpireAt'
        /// </summary>
        [Test]
        public void ExpireAtTest()
        {
            // TODO unit test for the property 'ExpireAt'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
