/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// BulkSession
    /// </summary>
    [DataContract(Name = "BulkSession")]
    public partial class BulkSession : IValidatableObject
    {
        /// <summary>
        /// * **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended 
        /// </summary>
        /// <value>* **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum N for value: n
            /// </summary>
            [EnumMember(Value = "n")]
            N = 1,

            /// <summary>
            /// Enum W for value: w
            /// </summary>
            [EnumMember(Value = "w")]
            W = 2,

            /// <summary>
            /// Enum F for value: f
            /// </summary>
            [EnumMember(Value = "f")]
            F = 3,

            /// <summary>
            /// Enum C for value: c
            /// </summary>
            [EnumMember(Value = "c")]
            C = 4,

            /// <summary>
            /// Enum S for value: s
            /// </summary>
            [EnumMember(Value = "s")]
            S = 5
        }


        /// <summary>
        /// * **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended 
        /// </summary>
        /// <value>* **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended </value>
        /*
        <example>n</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkSession" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BulkSession() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkSession" /> class.
        /// </summary>
        /// <param name="id">Bulk Session ID. (required).</param>
        /// <param name="status">* **n** – bulk session is just created * **w** - work in progress * **f** - failed * **c** - completed with success * **s** - suspended  (required).</param>
        /// <param name="itemsProcessed">Amount of messages already processed. (required).</param>
        /// <param name="itemsTotal">Total amount of messages to be processed. (required).</param>
        /// <param name="createdAt">Creation date and time of a Bulk Session. (required).</param>
        /// <param name="session">session (required).</param>
        /// <param name="text">Message text of a Bulk Session. (required).</param>
        public BulkSession(int id = default, StatusEnum status = default, int? itemsProcessed = default, int? itemsTotal = default, DateTime createdAt = default, MessageSession session = default, string text = default)
        {
            this.Id = id;
            this.Status = status;
            // to ensure "itemsProcessed" is required (not null)
            if (itemsProcessed == null)
            {
                throw new ArgumentNullException("itemsProcessed is a required property for BulkSession and cannot be null");
            }
            this.ItemsProcessed = itemsProcessed;
            // to ensure "itemsTotal" is required (not null)
            if (itemsTotal == null)
            {
                throw new ArgumentNullException("itemsTotal is a required property for BulkSession and cannot be null");
            }
            this.ItemsTotal = itemsTotal;
            this.CreatedAt = createdAt;
            // to ensure "session" is required (not null)
            if (session == null)
            {
                throw new ArgumentNullException("session is a required property for BulkSession and cannot be null");
            }
            this.Session = session;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for BulkSession and cannot be null");
            }
            this.Text = text;
        }

        /// <summary>
        /// Bulk Session ID.
        /// </summary>
        /// <value>Bulk Session ID.</value>
        /*
        <example>599</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Amount of messages already processed.
        /// </summary>
        /// <value>Amount of messages already processed.</value>
        /*
        <example>564</example>
        */
        [DataMember(Name = "itemsProcessed", IsRequired = true, EmitDefaultValue = true)]
        public int? ItemsProcessed { get; set; }

        /// <summary>
        /// Total amount of messages to be processed.
        /// </summary>
        /// <value>Total amount of messages to be processed.</value>
        /*
        <example>2</example>
        */
        [DataMember(Name = "itemsTotal", IsRequired = true, EmitDefaultValue = true)]
        public int? ItemsTotal { get; set; }

        /// <summary>
        /// Creation date and time of a Bulk Session.
        /// </summary>
        /// <value>Creation date and time of a Bulk Session.</value>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Session
        /// </summary>
        [DataMember(Name = "session", IsRequired = true, EmitDefaultValue = true)]
        public MessageSession Session { get; set; }

        /// <summary>
        /// Message text of a Bulk Session.
        /// </summary>
        /// <value>Message text of a Bulk Session.</value>
        /*
        <example>I Love Textmagic!</example>
        */
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkSession {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ItemsProcessed: ").Append(ItemsProcessed).Append("\n");
            sb.Append("  ItemsTotal: ").Append(ItemsTotal).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
