/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// CreateEmailCampaignRequest
    /// </summary>
    [DataContract(Name = "createEmailCampaign_request")]
    public partial class CreateEmailCampaignRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEmailCampaignRequest" /> class.
        /// </summary>
        /// <param name="emailSenderId">Email sender ID from your configured senders..</param>
        /// <param name="subject">Email subject line..</param>
        /// <param name="message">HTML email content..</param>
        /// <param name="fromName">Optional custom sender name..</param>
        /// <param name="replyToEmail">Optional custom reply-to email address..</param>
        /// <param name="recipients">recipients.</param>
        public CreateEmailCampaignRequest(int emailSenderId = default, string subject = default, string message = default, string fromName = default, string replyToEmail = default, CreateEmailCampaignRequestRecipients recipients = default)
        {
            this.EmailSenderId = emailSenderId;
            this.Subject = subject;
            this.Message = message;
            this.FromName = fromName;
            this.ReplyToEmail = replyToEmail;
            this.Recipients = recipients;
        }

        /// <summary>
        /// Email sender ID from your configured senders.
        /// </summary>
        /// <value>Email sender ID from your configured senders.</value>
        /*
        <example>123</example>
        */
        [DataMember(Name = "emailSenderId", EmitDefaultValue = false)]
        public int EmailSenderId { get; set; }

        /// <summary>
        /// Email subject line.
        /// </summary>
        /// <value>Email subject line.</value>
        /*
        <example>Special Offer - 50% Off Today Only!</example>
        */
        [DataMember(Name = "subject", EmitDefaultValue = false)]
        public string Subject { get; set; }

        /// <summary>
        /// HTML email content.
        /// </summary>
        /// <value>HTML email content.</value>
        /*
        <example>&lt;html&gt;&lt;body&gt;&lt;h1&gt;Special Offer!&lt;/h1&gt;&lt;p&gt;Get 50% off all products today only!&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</example>
        */
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Optional custom sender name.
        /// </summary>
        /// <value>Optional custom sender name.</value>
        /*
        <example>John Smith</example>
        */
        [DataMember(Name = "fromName", EmitDefaultValue = true)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional custom reply-to email address.
        /// </summary>
        /// <value>Optional custom reply-to email address.</value>
        /*
        <example>support@example.com</example>
        */
        [DataMember(Name = "replyToEmail", EmitDefaultValue = true)]
        public string ReplyToEmail { get; set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [DataMember(Name = "recipients", EmitDefaultValue = false)]
        public CreateEmailCampaignRequestRecipients Recipients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEmailCampaignRequest {\n");
            sb.Append("  EmailSenderId: ").Append(EmailSenderId).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ReplyToEmail: ").Append(ReplyToEmail).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Subject (string) maxLength
            if (this.Subject != null && this.Subject.Length > 998)
            {
                yield return new ValidationResult("Invalid value for Subject, length must be less than 998.", new [] { "Subject" });
            }

            // FromName (string) maxLength
            if (this.FromName != null && this.FromName.Length > 500)
            {
                yield return new ValidationResult("Invalid value for FromName, length must be less than 500.", new [] { "FromName" });
            }

            yield break;
        }
    }

}
