/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// Currency
    /// </summary>
    [DataContract(Name = "Currency")]
    public partial class Currency : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Currency" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Currency()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="Currency" /> class.
        /// </summary>
        /// <param name="id">The 3-letter ISO currency ID. (required).</param>
        /// <param name="unicodeSymbol">Unicode-compatible currency symbol. (required).</param>
        /// <param name="htmlSymbol">HTML-compatible currency symbol. (required).</param>
        public Currency(string id = default, string unicodeSymbol = default, string htmlSymbol = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Currency and cannot be null");
            }
            this.Id = id;
            // to ensure "unicodeSymbol" is required (not null)
            if (unicodeSymbol == null)
            {
                throw new ArgumentNullException("unicodeSymbol is a required property for Currency and cannot be null");
            }
            this.UnicodeSymbol = unicodeSymbol;
            // to ensure "htmlSymbol" is required (not null)
            if (htmlSymbol == null)
            {
                throw new ArgumentNullException("htmlSymbol is a required property for Currency and cannot be null");
            }
            this.HtmlSymbol = htmlSymbol;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// The 3-letter ISO currency ID.
        /// </summary>
        /// <value>The 3-letter ISO currency ID.</value>
        /*
        <example>GBP</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Unicode-compatible currency symbol.
        /// </summary>
        /// <value>Unicode-compatible currency symbol.</value>
        /*
        <example>£</example>
        */
        [DataMember(Name = "unicodeSymbol", IsRequired = true, EmitDefaultValue = true)]
        public string UnicodeSymbol { get; set; }

        /// <summary>
        /// HTML-compatible currency symbol.
        /// </summary>
        /// <value>HTML-compatible currency symbol.</value>
        /*
        <example>&amp;pound;</example>
        */
        [DataMember(Name = "htmlSymbol", IsRequired = true, EmitDefaultValue = true)]
        public string HtmlSymbol { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Currency {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UnicodeSymbol: ").Append(UnicodeSymbol).Append("\n");
            sb.Append("  HtmlSymbol: ").Append(HtmlSymbol).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
