/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// DoAuthResponseMinVersions
    /// </summary>
    [DataContract(Name = "DoAuthResponse_minVersions")]
    public partial class DoAuthResponseMinVersions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DoAuthResponseMinVersions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DoAuthResponseMinVersions()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="DoAuthResponseMinVersions" /> class.
        /// </summary>
        /// <param name="ios">ios (required).</param>
        /// <param name="android">android (required).</param>
        /// <param name="desktop">desktop (required).</param>
        public DoAuthResponseMinVersions(string ios = default, string android = default, string desktop = default)
        {
            // to ensure "ios" is required (not null)
            if (ios == null)
            {
                throw new ArgumentNullException("ios is a required property for DoAuthResponseMinVersions and cannot be null");
            }
            this.Ios = ios;
            // to ensure "android" is required (not null)
            if (android == null)
            {
                throw new ArgumentNullException("android is a required property for DoAuthResponseMinVersions and cannot be null");
            }
            this.Android = android;
            // to ensure "desktop" is required (not null)
            if (desktop == null)
            {
                throw new ArgumentNullException("desktop is a required property for DoAuthResponseMinVersions and cannot be null");
            }
            this.Desktop = desktop;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Ios
        /// </summary>
        /*
        <example>0</example>
        */
        [DataMember(Name = "ios", IsRequired = true, EmitDefaultValue = true)]
        public string Ios { get; set; }

        /// <summary>
        /// Gets or Sets Android
        /// </summary>
        /*
        <example>0</example>
        */
        [DataMember(Name = "android", IsRequired = true, EmitDefaultValue = true)]
        public string Android { get; set; }

        /// <summary>
        /// Gets or Sets Desktop
        /// </summary>
        /*
        <example>0</example>
        */
        [DataMember(Name = "desktop", IsRequired = true, EmitDefaultValue = true)]
        public string Desktop { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DoAuthResponseMinVersions {\n");
            sb.Append("  Ios: ").Append(Ios).Append("\n");
            sb.Append("  Android: ").Append(Android).Append("\n");
            sb.Append("  Desktop: ").Append(Desktop).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
