/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// DoCarrierLookupResponse
    /// </summary>
    [DataContract(Name = "DoCarrierLookupResponse")]
    public partial class DoCarrierLookupResponse : IValidatableObject
    {
        /// <summary>
        /// Phone number type.
        /// </summary>
        /// <value>Phone number type.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Mobile for value: mobile
            /// </summary>
            [EnumMember(Value = "mobile")]
            Mobile = 1,

            /// <summary>
            /// Enum Landline for value: landline
            /// </summary>
            [EnumMember(Value = "landline")]
            Landline = 2,

            /// <summary>
            /// Enum Voip for value: voip
            /// </summary>
            [EnumMember(Value = "voip")]
            Voip = 3
        }


        /// <summary>
        /// Phone number type.
        /// </summary>
        /// <value>Phone number type.</value>
        /*
        <example>mobile</example>
        */
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DoCarrierLookupResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DoCarrierLookupResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DoCarrierLookupResponse" /> class.
        /// </summary>
        /// <param name="cost">The cost to check that one number is constant – 0.04 in your account currency. (required).</param>
        /// <param name="country">country.</param>
        /// <param name="local">Phone number in [National format](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers). (required).</param>
        /// <param name="type">Phone number type. (required).</param>
        /// <param name="carrier">Carrier name. (required).</param>
        /// <param name="number164">Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164). (required).</param>
        /// <param name="valid">This field shows whether the entered phone number is valid or not. (required).</param>
        public DoCarrierLookupResponse(decimal cost = default, Country country = default, string local = default, TypeEnum type = default, string carrier = default, string number164 = default, bool valid = default)
        {
            this.Cost = cost;
            // to ensure "local" is required (not null)
            if (local == null)
            {
                throw new ArgumentNullException("local is a required property for DoCarrierLookupResponse and cannot be null");
            }
            this.Local = local;
            this.Type = type;
            // to ensure "carrier" is required (not null)
            if (carrier == null)
            {
                throw new ArgumentNullException("carrier is a required property for DoCarrierLookupResponse and cannot be null");
            }
            this.Carrier = carrier;
            // to ensure "number164" is required (not null)
            if (number164 == null)
            {
                throw new ArgumentNullException("number164 is a required property for DoCarrierLookupResponse and cannot be null");
            }
            this.Number164 = number164;
            this.Valid = valid;
            this.Country = country;
        }

        /// <summary>
        /// The cost to check that one number is constant – 0.04 in your account currency.
        /// </summary>
        /// <value>The cost to check that one number is constant – 0.04 in your account currency.</value>
        /*
        <example>0.04</example>
        */
        [DataMember(Name = "cost", IsRequired = true, EmitDefaultValue = true)]
        public decimal Cost { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = true)]
        public Country Country { get; set; }

        /// <summary>
        /// Phone number in [National format](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers).
        /// </summary>
        /// <value>Phone number in [National format](https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers).</value>
        /*
        <example>07860</example>
        */
        [DataMember(Name = "local", IsRequired = true, EmitDefaultValue = true)]
        public string Local { get; set; }

        /// <summary>
        /// Carrier name.
        /// </summary>
        /// <value>Carrier name.</value>
        /*
        <example>Telefonica UK</example>
        */
        [DataMember(Name = "carrier", IsRequired = true, EmitDefaultValue = true)]
        public string Carrier { get; set; }

        /// <summary>
        /// Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
        /// </summary>
        /// <value>Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).</value>
        /*
        <example>447860021130</example>
        */
        [DataMember(Name = "number164", IsRequired = true, EmitDefaultValue = true)]
        public string Number164 { get; set; }

        /// <summary>
        /// This field shows whether the entered phone number is valid or not.
        /// </summary>
        /// <value>This field shows whether the entered phone number is valid or not.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "valid", IsRequired = true, EmitDefaultValue = true)]
        public bool Valid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DoCarrierLookupResponse {\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Local: ").Append(Local).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Carrier: ").Append(Carrier).Append("\n");
            sb.Append("  Number164: ").Append(Number164).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
