/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// GetMessagingCountersResponse
    /// </summary>
    [DataContract(Name = "GetMessagingCountersResponse")]
    public partial class GetMessagingCountersResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMessagingCountersResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMessagingCountersResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMessagingCountersResponse" /> class.
        /// </summary>
        /// <param name="contacts">Total contacts amount. (required).</param>
        /// <param name="sent">Total sent messages amount. (required).</param>
        /// <param name="received">Total received messages amount. (required).</param>
        public GetMessagingCountersResponse(int contacts = default, int sent = default, int received = default)
        {
            this.Contacts = contacts;
            this.Sent = sent;
            this.Received = received;
        }

        /// <summary>
        /// Total contacts amount.
        /// </summary>
        /// <value>Total contacts amount.</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "contacts", IsRequired = true, EmitDefaultValue = true)]
        public int Contacts { get; set; }

        /// <summary>
        /// Total sent messages amount.
        /// </summary>
        /// <value>Total sent messages amount.</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "sent", IsRequired = true, EmitDefaultValue = true)]
        public int Sent { get; set; }

        /// <summary>
        /// Total received messages amount.
        /// </summary>
        /// <value>Total received messages amount.</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "received", IsRequired = true, EmitDefaultValue = true)]
        public int Received { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMessagingCountersResponse {\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  Sent: ").Append(Sent).Append("\n");
            sb.Append("  Received: ").Append(Received).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
