/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// GetMessageSessionStatResponse
    /// </summary>
    [DataContract(Name = "GetMessageSessionStatResponse")]
    public partial class GetMessageSessionStatResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMessageSessionStatResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetMessageSessionStatResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMessageSessionStatResponse" /> class.
        /// </summary>
        /// <param name="failed">Amount of failed messages. (required).</param>
        /// <param name="delivered">Amount of delivered messages. (required).</param>
        /// <param name="accepted">Amount of accepted messages. (required).</param>
        /// <param name="rejected">Amount of rejected messages. (required).</param>
        /// <param name="scheduled">Amount of scheduled messages. (required).</param>
        /// <param name="all">Total amount of messages. (required).</param>
        /// <param name="sent">Amount of sent but not yet delivered messages. (required).</param>
        public GetMessageSessionStatResponse(int failed = default, int delivered = default, int accepted = default, int rejected = default, int scheduled = default, int all = default, int sent = default)
        {
            this.Failed = failed;
            this.Delivered = delivered;
            this.Accepted = accepted;
            this.Rejected = rejected;
            this.Scheduled = scheduled;
            this.All = all;
            this.Sent = sent;
        }

        /// <summary>
        /// Amount of failed messages.
        /// </summary>
        /// <value>Amount of failed messages.</value>
        /*
        <example>12</example>
        */
        [DataMember(Name = "failed", IsRequired = true, EmitDefaultValue = true)]
        public int Failed { get; set; }

        /// <summary>
        /// Amount of delivered messages.
        /// </summary>
        /// <value>Amount of delivered messages.</value>
        /*
        <example>99</example>
        */
        [DataMember(Name = "delivered", IsRequired = true, EmitDefaultValue = true)]
        public int Delivered { get; set; }

        /// <summary>
        /// Amount of accepted messages.
        /// </summary>
        /// <value>Amount of accepted messages.</value>
        /*
        <example>75</example>
        */
        [DataMember(Name = "accepted", IsRequired = true, EmitDefaultValue = true)]
        public int Accepted { get; set; }

        /// <summary>
        /// Amount of rejected messages.
        /// </summary>
        /// <value>Amount of rejected messages.</value>
        /*
        <example>12</example>
        */
        [DataMember(Name = "rejected", IsRequired = true, EmitDefaultValue = true)]
        public int Rejected { get; set; }

        /// <summary>
        /// Amount of scheduled messages.
        /// </summary>
        /// <value>Amount of scheduled messages.</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "scheduled", IsRequired = true, EmitDefaultValue = true)]
        public int Scheduled { get; set; }

        /// <summary>
        /// Total amount of messages.
        /// </summary>
        /// <value>Total amount of messages.</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "all", IsRequired = true, EmitDefaultValue = true)]
        public int All { get; set; }

        /// <summary>
        /// Amount of sent but not yet delivered messages.
        /// </summary>
        /// <value>Amount of sent but not yet delivered messages.</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "sent", IsRequired = true, EmitDefaultValue = true)]
        public int Sent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMessageSessionStatResponse {\n");
            sb.Append("  Failed: ").Append(Failed).Append("\n");
            sb.Append("  Delivered: ").Append(Delivered).Append("\n");
            sb.Append("  Accepted: ").Append(Accepted).Append("\n");
            sb.Append("  Rejected: ").Append(Rejected).Append("\n");
            sb.Append("  Scheduled: ").Append(Scheduled).Append("\n");
            sb.Append("  All: ").Append(All).Append("\n");
            sb.Append("  Sent: ").Append(Sent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
