/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// GetUnreadMessagesTotalResponse
    /// </summary>
    [DataContract(Name = "GetUnreadMessagesTotalResponse")]
    public partial class GetUnreadMessagesTotalResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUnreadMessagesTotalResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUnreadMessagesTotalResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUnreadMessagesTotalResponse" /> class.
        /// </summary>
        /// <param name="total">Amount of unread messages. (required).</param>
        public GetUnreadMessagesTotalResponse(int total = default)
        {
            this.Total = total;
        }

        /// <summary>
        /// Amount of unread messages.
        /// </summary>
        /// <value>Amount of unread messages.</value>
        /*
        <example>22</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUnreadMessagesTotalResponse {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
