/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// MessageOut
    /// </summary>
    [DataContract(Name = "MessageOut")]
    public partial class MessageOut : IValidatableObject
    {
        /// <summary>
        /// Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. 
        /// </summary>
        /// <value>Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Q for value: q
            /// </summary>
            [EnumMember(Value = "q")]
            Q = 1,

            /// <summary>
            /// Enum S for value: s
            /// </summary>
            [EnumMember(Value = "s")]
            S = 2,

            /// <summary>
            /// Enum E for value: e
            /// </summary>
            [EnumMember(Value = "e")]
            E = 3,

            /// <summary>
            /// Enum R for value: r
            /// </summary>
            [EnumMember(Value = "r")]
            R = 4,

            /// <summary>
            /// Enum A for value: a
            /// </summary>
            [EnumMember(Value = "a")]
            A = 5,

            /// <summary>
            /// Enum D for value: d
            /// </summary>
            [EnumMember(Value = "d")]
            D = 6,

            /// <summary>
            /// Enum B for value: b
            /// </summary>
            [EnumMember(Value = "b")]
            B = 7,

            /// <summary>
            /// Enum F for value: f
            /// </summary>
            [EnumMember(Value = "f")]
            F = 8,

            /// <summary>
            /// Enum U for value: u
            /// </summary>
            [EnumMember(Value = "u")]
            U = 9,

            /// <summary>
            /// Enum J for value: j
            /// </summary>
            [EnumMember(Value = "j")]
            J = 10,

            /// <summary>
            /// Enum I for value: i
            /// </summary>
            [EnumMember(Value = "i")]
            I = 11,

            /// <summary>
            /// Enum P for value: p
            /// </summary>
            [EnumMember(Value = "p")]
            P = 12,

            /// <summary>
            /// Enum H for value: h
            /// </summary>
            [EnumMember(Value = "h")]
            H = 13
        }


        /// <summary>
        /// Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. 
        /// </summary>
        /// <value>Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details. </value>
        /*
        <example>d</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Rejection reason.
        /// </summary>
        /// <value>Rejection reason.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RejectReasonEnum
        {
            /// <summary>
            /// Enum A for value: a
            /// </summary>
            [EnumMember(Value = "a")]
            A = 1,

            /// <summary>
            /// Enum F for value: f
            /// </summary>
            [EnumMember(Value = "f")]
            F = 2,

            /// <summary>
            /// Enum L for value: l
            /// </summary>
            [EnumMember(Value = "l")]
            L = 3,

            /// <summary>
            /// Enum C for value: c
            /// </summary>
            [EnumMember(Value = "c")]
            C = 4,

            /// <summary>
            /// Enum U for value: u
            /// </summary>
            [EnumMember(Value = "u")]
            U = 5,

            /// <summary>
            /// Enum B for value: b
            /// </summary>
            [EnumMember(Value = "b")]
            B = 6,

            /// <summary>
            /// Enum S for value: s
            /// </summary>
            [EnumMember(Value = "s")]
            S = 7,

            /// <summary>
            /// Enum M for value: m
            /// </summary>
            [EnumMember(Value = "m")]
            M = 8,

            /// <summary>
            /// Enum N for value: n
            /// </summary>
            [EnumMember(Value = "n")]
            N = 9,

            /// <summary>
            /// Enum I for value: i
            /// </summary>
            [EnumMember(Value = "i")]
            I = 10,

            /// <summary>
            /// Enum If for value: if
            /// </summary>
            [EnumMember(Value = "if")]
            If = 11,

            /// <summary>
            /// Enum D for value: d
            /// </summary>
            [EnumMember(Value = "d")]
            D = 12,

            /// <summary>
            /// Enum T for value: t
            /// </summary>
            [EnumMember(Value = "t")]
            T = 13,

            /// <summary>
            /// Enum E for value: e
            /// </summary>
            [EnumMember(Value = "e")]
            E = 14,

            /// <summary>
            /// Enum H for value: h
            /// </summary>
            [EnumMember(Value = "h")]
            H = 15,

            /// <summary>
            /// Enum K for value: k
            /// </summary>
            [EnumMember(Value = "k")]
            K = 16,

            /// <summary>
            /// Enum R for value: r
            /// </summary>
            [EnumMember(Value = "r")]
            R = 17,

            /// <summary>
            /// Enum G for value: g
            /// </summary>
            [EnumMember(Value = "g")]
            G = 18,

            /// <summary>
            /// Enum J for value: j
            /// </summary>
            [EnumMember(Value = "j")]
            J = 19,

            /// <summary>
            /// Enum W for value: w
            /// </summary>
            [EnumMember(Value = "w")]
            W = 20,

            /// <summary>
            /// Enum V for value: v
            /// </summary>
            [EnumMember(Value = "v")]
            V = 21,

            /// <summary>
            /// Enum Q for value: q
            /// </summary>
            [EnumMember(Value = "q")]
            Q = 22,

            /// <summary>
            /// Enum X for value: x
            /// </summary>
            [EnumMember(Value = "x")]
            X = 23,

            /// <summary>
            /// Enum O for value: o
            /// </summary>
            [EnumMember(Value = "o")]
            O = 24,

            /// <summary>
            /// Enum P for value: p
            /// </summary>
            [EnumMember(Value = "p")]
            P = 25
        }


        /// <summary>
        /// Rejection reason.
        /// </summary>
        /// <value>Rejection reason.</value>
        /*
        <example>a</example>
        */
        [DataMember(Name = "rejectReason", EmitDefaultValue = false)]
        public RejectReasonEnum? RejectReason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageOut" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessageOut() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageOut" /> class.
        /// </summary>
        /// <param name="id">Message ID. (required).</param>
        /// <param name="sender">Message sender (phone number or alphanumeric Sender ID)..</param>
        /// <param name="receiver">Recipient&#x60;s phone number..</param>
        /// <param name="text">text (required).</param>
        /// <param name="status">Delivery status of the message. See [message delivery statuses](https://docs.textmagic.com/#section/Delivery-status-codes) for details.  (required).</param>
        /// <param name="rejectReason">Rejection reason..</param>
        /// <param name="contactId">Recipient contact ID. (required).</param>
        /// <param name="sessionId">Message Session ID of a message. (required).</param>
        /// <param name="messageTime">Sending time. (required).</param>
        /// <param name="avatar">avatar (required).</param>
        /// <param name="deleted">Indicates that the message has been deleted..</param>
        /// <param name="charset">Message charset. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS.  (required).</param>
        /// <param name="charsetLabel">Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages.  (required).</param>
        /// <param name="firstName">Contact first name. Could be substituted from your [Contacts](https://docs.textmagic.com/#tag/Contacts) (even if you submitted the phone number instead of the contact ID).  (required).</param>
        /// <param name="lastName">Contact last name. (required).</param>
        /// <param name="country">The 2-letter ISO country code of the recipient&#39;s phone number.  (required).</param>
        /// <param name="phone">Receipent&#x60;s phone number..</param>
        /// <param name="price">Message price..</param>
        /// <param name="partsCount">Message parts (multiples of 160 characters) count. (required).</param>
        /// <param name="fromEmail">The user email which this message came from. For Email2SMS and Distribution Lists the messages, it is an original email address - in other cases, it is an account email address..</param>
        /// <param name="fromNumber">The Phone number used to send the SMS..</param>
        /// <param name="senderSource">senderSource.</param>
        /// <param name="session">session.</param>
        public MessageOut(int id = default, string sender = default, string receiver = default, string text = default, StatusEnum status = default, RejectReasonEnum? rejectReason = default, int? contactId = default, int? sessionId = default, DateTime messageTime = default, string avatar = default, bool deleted = default, string charset = default, string charsetLabel = default, string firstName = default, string lastName = default, string country = default, string phone = default, float? price = default, int? partsCount = default, string fromEmail = default, string fromNumber = default, MessageOutSenderSource senderSource = default, MessageOutSession session = default)
        {
            this.Id = id;
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for MessageOut and cannot be null");
            }
            this.Text = text;
            this.Status = status;
            // to ensure "contactId" is required (not null)
            if (contactId == null)
            {
                throw new ArgumentNullException("contactId is a required property for MessageOut and cannot be null");
            }
            this.ContactId = contactId;
            // to ensure "sessionId" is required (not null)
            if (sessionId == null)
            {
                throw new ArgumentNullException("sessionId is a required property for MessageOut and cannot be null");
            }
            this.SessionId = sessionId;
            this.MessageTime = messageTime;
            // to ensure "avatar" is required (not null)
            if (avatar == null)
            {
                throw new ArgumentNullException("avatar is a required property for MessageOut and cannot be null");
            }
            this.Avatar = avatar;
            // to ensure "charset" is required (not null)
            if (charset == null)
            {
                throw new ArgumentNullException("charset is a required property for MessageOut and cannot be null");
            }
            this.Charset = charset;
            // to ensure "charsetLabel" is required (not null)
            if (charsetLabel == null)
            {
                throw new ArgumentNullException("charsetLabel is a required property for MessageOut and cannot be null");
            }
            this.CharsetLabel = charsetLabel;
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName is a required property for MessageOut and cannot be null");
            }
            this.FirstName = firstName;
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName is a required property for MessageOut and cannot be null");
            }
            this.LastName = lastName;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for MessageOut and cannot be null");
            }
            this.Country = country;
            // to ensure "partsCount" is required (not null)
            if (partsCount == null)
            {
                throw new ArgumentNullException("partsCount is a required property for MessageOut and cannot be null");
            }
            this.PartsCount = partsCount;
            this.Sender = sender;
            this.Receiver = receiver;
            this.RejectReason = rejectReason;
            this.Deleted = deleted;
            this.Phone = phone;
            this.Price = price;
            this.FromEmail = fromEmail;
            this.FromNumber = fromNumber;
            this.SenderSource = senderSource;
            this.Session = session;
        }

        /// <summary>
        /// Message ID.
        /// </summary>
        /// <value>Message ID.</value>
        /*
        <example>4991</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Message sender (phone number or alphanumeric Sender ID).
        /// </summary>
        /// <value>Message sender (phone number or alphanumeric Sender ID).</value>
        /*
        <example>447624800500</example>
        */
        [DataMember(Name = "sender", EmitDefaultValue = true)]
        public string Sender { get; set; }

        /// <summary>
        /// Recipient&#x60;s phone number.
        /// </summary>
        /// <value>Recipient&#x60;s phone number.</value>
        /*
        <example>447860021130</example>
        */
        [DataMember(Name = "receiver", EmitDefaultValue = false)]
        public string Receiver { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        /*
        <example>I love Textmagic!</example>
        */
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Recipient contact ID.
        /// </summary>
        /// <value>Recipient contact ID.</value>
        /*
        <example>2764</example>
        */
        [DataMember(Name = "contactId", IsRequired = true, EmitDefaultValue = true)]
        public int? ContactId { get; set; }

        /// <summary>
        /// Message Session ID of a message.
        /// </summary>
        /// <value>Message Session ID of a message.</value>
        /*
        <example>3122</example>
        */
        [DataMember(Name = "sessionId", IsRequired = true, EmitDefaultValue = true)]
        public int? SessionId { get; set; }

        /// <summary>
        /// Sending time.
        /// </summary>
        /// <value>Sending time.</value>
        [DataMember(Name = "messageTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime MessageTime { get; set; }

        /// <summary>
        /// Gets or Sets Avatar
        /// </summary>
        /*
        <example>avatars/dummy_avatar.png</example>
        */
        [DataMember(Name = "avatar", IsRequired = true, EmitDefaultValue = true)]
        public string Avatar { get; set; }

        /// <summary>
        /// Indicates that the message has been deleted.
        /// </summary>
        /// <value>Indicates that the message has been deleted.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "deleted", EmitDefaultValue = true)]
        public bool Deleted { get; set; }

        /// <summary>
        /// Message charset. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS. 
        /// </summary>
        /// <value>Message charset. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS. </value>
        /*
        <example>ISO-8859-1</example>
        */
        [DataMember(Name = "charset", IsRequired = true, EmitDefaultValue = true)]
        public string Charset { get; set; }

        /// <summary>
        /// Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. 
        /// </summary>
        /// <value>Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. </value>
        /*
        <example>ISO-8859-1</example>
        */
        [DataMember(Name = "charsetLabel", IsRequired = true, EmitDefaultValue = true)]
        public string CharsetLabel { get; set; }

        /// <summary>
        /// Contact first name. Could be substituted from your [Contacts](https://docs.textmagic.com/#tag/Contacts) (even if you submitted the phone number instead of the contact ID). 
        /// </summary>
        /// <value>Contact first name. Could be substituted from your [Contacts](https://docs.textmagic.com/#tag/Contacts) (even if you submitted the phone number instead of the contact ID). </value>
        /*
        <example>John</example>
        */
        [DataMember(Name = "firstName", IsRequired = true, EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Contact last name.
        /// </summary>
        /// <value>Contact last name.</value>
        /*
        <example>Conway</example>
        */
        [DataMember(Name = "lastName", IsRequired = true, EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// The 2-letter ISO country code of the recipient&#39;s phone number. 
        /// </summary>
        /// <value>The 2-letter ISO country code of the recipient&#39;s phone number. </value>
        /*
        <example>US</example>
        */
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Receipent&#x60;s phone number.
        /// </summary>
        /// <value>Receipent&#x60;s phone number.</value>
        /*
        <example>447624800500</example>
        */
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Message price.
        /// </summary>
        /// <value>Message price.</value>
        /*
        <example>0.025</example>
        */
        [DataMember(Name = "price", EmitDefaultValue = true)]
        public float? Price { get; set; }

        /// <summary>
        /// Message parts (multiples of 160 characters) count.
        /// </summary>
        /// <value>Message parts (multiples of 160 characters) count.</value>
        /*
        <example>6</example>
        */
        [DataMember(Name = "partsCount", IsRequired = true, EmitDefaultValue = true)]
        public int? PartsCount { get; set; }

        /// <summary>
        /// The user email which this message came from. For Email2SMS and Distribution Lists the messages, it is an original email address - in other cases, it is an account email address.
        /// </summary>
        /// <value>The user email which this message came from. For Email2SMS and Distribution Lists the messages, it is an original email address - in other cases, it is an account email address.</value>
        /*
        <example>test@email.com</example>
        */
        [DataMember(Name = "fromEmail", EmitDefaultValue = true)]
        public string FromEmail { get; set; }

        /// <summary>
        /// The Phone number used to send the SMS.
        /// </summary>
        /// <value>The Phone number used to send the SMS.</value>
        /*
        <example>447624800500</example>
        */
        [DataMember(Name = "fromNumber", EmitDefaultValue = true)]
        public string FromNumber { get; set; }

        /// <summary>
        /// Gets or Sets SenderSource
        /// </summary>
        [DataMember(Name = "senderSource", EmitDefaultValue = false)]
        public MessageOutSenderSource SenderSource { get; set; }

        /// <summary>
        /// Gets or Sets Session
        /// </summary>
        [DataMember(Name = "session", EmitDefaultValue = false)]
        public MessageOutSession Session { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessageOut {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Sender: ").Append(Sender).Append("\n");
            sb.Append("  Receiver: ").Append(Receiver).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RejectReason: ").Append(RejectReason).Append("\n");
            sb.Append("  ContactId: ").Append(ContactId).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  MessageTime: ").Append(MessageTime).Append("\n");
            sb.Append("  Avatar: ").Append(Avatar).Append("\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("  Charset: ").Append(Charset).Append("\n");
            sb.Append("  CharsetLabel: ").Append(CharsetLabel).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  PartsCount: ").Append(PartsCount).Append("\n");
            sb.Append("  FromEmail: ").Append(FromEmail).Append("\n");
            sb.Append("  FromNumber: ").Append(FromNumber).Append("\n");
            sb.Append("  SenderSource: ").Append(SenderSource).Append("\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
