/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// MessagesIcsTextParameters
    /// </summary>
    [DataContract(Name = "MessagesIcs_textParameters")]
    public partial class MessagesIcsTextParameters : IValidatableObject
    {
        /// <summary>
        /// Message charset. Could be: * **ISO-8859-1** – for plaintext SMS; * **UTF-16BE** – for Unicode SMS. 
        /// </summary>
        /// <value>Message charset. Could be: * **ISO-8859-1** – for plaintext SMS; * **UTF-16BE** – for Unicode SMS. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EncodingEnum
        {
            /// <summary>
            /// Enum ISO88591 for value: ISO-8859-1
            /// </summary>
            [EnumMember(Value = "ISO-8859-1")]
            ISO88591 = 1,

            /// <summary>
            /// Enum UTF16BE for value: UTF-16BE
            /// </summary>
            [EnumMember(Value = "UTF-16BE")]
            UTF16BE = 2
        }


        /// <summary>
        /// Message charset. Could be: * **ISO-8859-1** – for plaintext SMS; * **UTF-16BE** – for Unicode SMS. 
        /// </summary>
        /// <value>Message charset. Could be: * **ISO-8859-1** – for plaintext SMS; * **UTF-16BE** – for Unicode SMS. </value>
        /*
        <example>ISO-8859-1</example>
        */
        [DataMember(Name = "encoding", IsRequired = true, EmitDefaultValue = true)]
        public EncodingEnum Encoding { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesIcsTextParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesIcsTextParameters()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesIcsTextParameters" /> class.
        /// </summary>
        /// <param name="cost">Cost to check that one number is constant – 0.04 in your account currency. (required).</param>
        /// <param name="parts">Message parts (multiples of 160 characters) count. (required).</param>
        /// <param name="chars">Characters count. (required).</param>
        /// <param name="encoding">Message charset. Could be: * **ISO-8859-1** – for plaintext SMS; * **UTF-16BE** – for Unicode SMS.  (required).</param>
        /// <param name="countries">countries (required).</param>
        /// <param name="charsetLabel">Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages.  (required).</param>
        public MessagesIcsTextParameters(decimal? cost = default, int? parts = default, int? chars = default, EncodingEnum encoding = default, List<string> countries = default, string charsetLabel = default)
        {
            // to ensure "cost" is required (not null)
            if (cost == null)
            {
                throw new ArgumentNullException("cost is a required property for MessagesIcsTextParameters and cannot be null");
            }
            this.Cost = cost;
            // to ensure "parts" is required (not null)
            if (parts == null)
            {
                throw new ArgumentNullException("parts is a required property for MessagesIcsTextParameters and cannot be null");
            }
            this.Parts = parts;
            // to ensure "chars" is required (not null)
            if (chars == null)
            {
                throw new ArgumentNullException("chars is a required property for MessagesIcsTextParameters and cannot be null");
            }
            this.Chars = chars;
            this.Encoding = encoding;
            // to ensure "countries" is required (not null)
            if (countries == null)
            {
                throw new ArgumentNullException("countries is a required property for MessagesIcsTextParameters and cannot be null");
            }
            this.Countries = countries;
            // to ensure "charsetLabel" is required (not null)
            if (charsetLabel == null)
            {
                throw new ArgumentNullException("charsetLabel is a required property for MessagesIcsTextParameters and cannot be null");
            }
            this.CharsetLabel = charsetLabel;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Cost to check that one number is constant – 0.04 in your account currency.
        /// </summary>
        /// <value>Cost to check that one number is constant – 0.04 in your account currency.</value>
        /*
        <example>0.04</example>
        */
        [DataMember(Name = "cost", IsRequired = true, EmitDefaultValue = true)]
        public decimal? Cost { get; set; }

        /// <summary>
        /// Message parts (multiples of 160 characters) count.
        /// </summary>
        /// <value>Message parts (multiples of 160 characters) count.</value>
        /*
        <example>6</example>
        */
        [DataMember(Name = "parts", IsRequired = true, EmitDefaultValue = true)]
        public int? Parts { get; set; }

        /// <summary>
        /// Characters count.
        /// </summary>
        /// <value>Characters count.</value>
        /*
        <example>125</example>
        */
        [DataMember(Name = "chars", IsRequired = true, EmitDefaultValue = true)]
        public int? Chars { get; set; }

        /// <summary>
        /// Gets or Sets Countries
        /// </summary>
        [DataMember(Name = "countries", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Countries { get; set; }

        /// <summary>
        /// Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. 
        /// </summary>
        /// <value>Human-readable message charset label. Could be: *   **ISO-8859-1** for plaintext SMS; *   **UTF-16BE** for Unicode SMS; *   **Voice** for voice services (Text-to-Speech or Voice Broadcast) messages. </value>
        /*
        <example>ISO-8859-1</example>
        */
        [DataMember(Name = "charsetLabel", IsRequired = true, EmitDefaultValue = true)]
        public string CharsetLabel { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessagesIcsTextParameters {\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Parts: ").Append(Parts).Append("\n");
            sb.Append("  Chars: ").Append(Chars).Append("\n");
            sb.Append("  Encoding: ").Append(Encoding).Append("\n");
            sb.Append("  Countries: ").Append(Countries).Append("\n");
            sb.Append("  CharsetLabel: ").Append(CharsetLabel).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
