/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// MessagesIcsParameters
    /// </summary>
    [DataContract(Name = "MessagesIcs_parameters")]
    public partial class MessagesIcsParameters : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesIcsParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MessagesIcsParameters()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="MessagesIcsParameters" /> class.
        /// </summary>
        /// <param name="text">Scheduled message text. (required).</param>
        /// <param name="recipients">recipients (required).</param>
        public MessagesIcsParameters(string text = default, MessagesIcsParametersRecipients recipients = default)
        {
            // to ensure "text" is required (not null)
            if (text == null)
            {
                throw new ArgumentNullException("text is a required property for MessagesIcsParameters and cannot be null");
            }
            this.Text = text;
            // to ensure "recipients" is required (not null)
            if (recipients == null)
            {
                throw new ArgumentNullException("recipients is a required property for MessagesIcsParameters and cannot be null");
            }
            this.Recipients = recipients;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Scheduled message text.
        /// </summary>
        /// <value>Scheduled message text.</value>
        /*
        <example>I Love Textmagic!</example>
        */
        [DataMember(Name = "text", IsRequired = true, EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [DataMember(Name = "recipients", IsRequired = true, EmitDefaultValue = true)]
        public MessagesIcsParametersRecipients Recipients { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessagesIcsParameters {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
