/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// ScheduleEmailCampaignInputObject
    /// </summary>
    [DataContract]
    public partial class ScheduleEmailCampaignInputObject :  IEquatable<ScheduleEmailCampaignInputObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleEmailCampaignInputObject" /> class.
        /// </summary>
        /// <param name="emailSenderId">Email sender ID from your configured senders..</param>
        /// <param name="subject">Email subject line..</param>
        /// <param name="message">HTML email content..</param>
        /// <param name="fromName">Optional custom sender name..</param>
        /// <param name="replyToEmail">Optional custom reply-to email address..</param>
        /// <param name="recipients">recipients.</param>
        /// <param name="scheduleParams">scheduleParams.</param>
        public ScheduleEmailCampaignInputObject(int? emailSenderId = default(int?), string subject = default(string), string message = default(string), string fromName = default(string), string replyToEmail = default(string), Apiv2emailcampaignsscheduleRecipients recipients = default(Apiv2emailcampaignsscheduleRecipients), Apiv2emailcampaignsscheduleScheduleParams scheduleParams = default(Apiv2emailcampaignsscheduleScheduleParams))
        {
            this.EmailSenderId = emailSenderId;
            this.Subject = subject;
            this.Message = message;
            this.FromName = fromName;
            this.ReplyToEmail = replyToEmail;
            this.Recipients = recipients;
            this.ScheduleParams = scheduleParams;
        }
        
        /// <summary>
        /// Email sender ID from your configured senders.
        /// </summary>
        /// <value>Email sender ID from your configured senders.</value>
        [DataMember(Name="emailSenderId", EmitDefaultValue=false)]
        public int? EmailSenderId { get; set; }

        /// <summary>
        /// Email subject line.
        /// </summary>
        /// <value>Email subject line.</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// HTML email content.
        /// </summary>
        /// <value>HTML email content.</value>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public string Message { get; set; }

        /// <summary>
        /// Optional custom sender name.
        /// </summary>
        /// <value>Optional custom sender name.</value>
        [DataMember(Name="fromName", EmitDefaultValue=false)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional custom reply-to email address.
        /// </summary>
        /// <value>Optional custom reply-to email address.</value>
        [DataMember(Name="replyToEmail", EmitDefaultValue=false)]
        public string ReplyToEmail { get; set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [DataMember(Name="recipients", EmitDefaultValue=false)]
        public Apiv2emailcampaignsscheduleRecipients Recipients { get; set; }

        /// <summary>
        /// Gets or Sets ScheduleParams
        /// </summary>
        [DataMember(Name="scheduleParams", EmitDefaultValue=false)]
        public Apiv2emailcampaignsscheduleScheduleParams ScheduleParams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduleEmailCampaignInputObject {\n");
            sb.Append("  EmailSenderId: ").Append(EmailSenderId).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ReplyToEmail: ").Append(ReplyToEmail).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  ScheduleParams: ").Append(ScheduleParams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduleEmailCampaignInputObject);
        }

        /// <summary>
        /// Returns true if ScheduleEmailCampaignInputObject instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduleEmailCampaignInputObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduleEmailCampaignInputObject input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EmailSenderId == input.EmailSenderId ||
                    (this.EmailSenderId != null &&
                    this.EmailSenderId.Equals(input.EmailSenderId))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.FromName == input.FromName ||
                    (this.FromName != null &&
                    this.FromName.Equals(input.FromName))
                ) && 
                (
                    this.ReplyToEmail == input.ReplyToEmail ||
                    (this.ReplyToEmail != null &&
                    this.ReplyToEmail.Equals(input.ReplyToEmail))
                ) && 
                (
                    this.Recipients == input.Recipients ||
                    (this.Recipients != null &&
                    this.Recipients.Equals(input.Recipients))
                ) && 
                (
                    this.ScheduleParams == input.ScheduleParams ||
                    (this.ScheduleParams != null &&
                    this.ScheduleParams.Equals(input.ScheduleParams))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EmailSenderId != null)
                    hashCode = hashCode * 59 + this.EmailSenderId.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.FromName != null)
                    hashCode = hashCode * 59 + this.FromName.GetHashCode();
                if (this.ReplyToEmail != null)
                    hashCode = hashCode * 59 + this.ReplyToEmail.GetHashCode();
                if (this.Recipients != null)
                    hashCode = hashCode * 59 + this.Recipients.GetHashCode();
                if (this.ScheduleParams != null)
                    hashCode = hashCode * 59 + this.ScheduleParams.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Subject (string) maxLength
            if(this.Subject != null && this.Subject.Length > 998)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Subject, length must be less than 998.", new [] { "Subject" });
            }

            // FromName (string) maxLength
            if(this.FromName != null && this.FromName.Length > 500)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FromName, length must be less than 500.", new [] { "FromName" });
            }

            yield break;
        }
    }

}
