/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// ScheduledEmailCampaignDetails
    /// </summary>
    [DataContract]
    public partial class ScheduledEmailCampaignDetails :  IEquatable<ScheduledEmailCampaignDetails>, IValidatableObject
    {
        /// <summary>
        /// Current scheduled campaign status.
        /// </summary>
        /// <value>Current scheduled campaign status.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum Scheduled for value: scheduled
            /// </summary>
            [EnumMember(Value = "scheduled")]
            Scheduled = 1,
            
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 2,
            
            /// <summary>
            /// Enum Paused for value: paused
            /// </summary>
            [EnumMember(Value = "paused")]
            Paused = 3,
            
            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 4,
            
            /// <summary>
            /// Enum Cancelled for value: cancelled
            /// </summary>
            [EnumMember(Value = "cancelled")]
            Cancelled = 5,
            
            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 6
        }

        /// <summary>
        /// Current scheduled campaign status.
        /// </summary>
        /// <value>Current scheduled campaign status.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Campaign recurrence type.
        /// </summary>
        /// <value>Campaign recurrence type.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Once for value: once
            /// </summary>
            [EnumMember(Value = "once")]
            Once = 1,
            
            /// <summary>
            /// Enum Hourly for value: hourly
            /// </summary>
            [EnumMember(Value = "hourly")]
            Hourly = 2,
            
            /// <summary>
            /// Enum Daily for value: daily
            /// </summary>
            [EnumMember(Value = "daily")]
            Daily = 3,
            
            /// <summary>
            /// Enum Weekly for value: weekly
            /// </summary>
            [EnumMember(Value = "weekly")]
            Weekly = 4,
            
            /// <summary>
            /// Enum Monthly for value: monthly
            /// </summary>
            [EnumMember(Value = "monthly")]
            Monthly = 5,
            
            /// <summary>
            /// Enum Yearly for value: yearly
            /// </summary>
            [EnumMember(Value = "yearly")]
            Yearly = 6,
            
            /// <summary>
            /// Enum FollowUp for value: follow-up
            /// </summary>
            [EnumMember(Value = "follow-up")]
            FollowUp = 7
        }

        /// <summary>
        /// Campaign recurrence type.
        /// </summary>
        /// <value>Campaign recurrence type.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledEmailCampaignDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduledEmailCampaignDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduledEmailCampaignDetails" /> class.
        /// </summary>
        /// <param name="id">Unique scheduled campaign ID. (required).</param>
        /// <param name="status">Current scheduled campaign status. (required).</param>
        /// <param name="emailSenderId">Email sender ID used for this campaign..</param>
        /// <param name="startAt">Scheduled start timestamp (UTC). (required).</param>
        /// <param name="endAt">End timestamp for recurring campaigns (UTC)..</param>
        /// <param name="nextSendAt">Next scheduled send timestamp (UTC)..</param>
        /// <param name="createdBy">createdBy (required).</param>
        /// <param name="createdAt">Campaign creation timestamp. (required).</param>
        /// <param name="updatedAt">Last update timestamp. (required).</param>
        /// <param name="type">Campaign recurrence type. (required).</param>
        /// <param name="fromName">Sender name displayed in recipient&#39;s inbox..</param>
        /// <param name="fromEmail">Sender email address. (required).</param>
        /// <param name="replyToEmail">Reply-to email address. (required).</param>
        /// <param name="subject">Email subject line. (required).</param>
        /// <param name="html">HTML email content. (required).</param>
        /// <param name="recipientsCount">Number of recipients for this campaign. (required).</param>
        /// <param name="sendingTimezone">Timezone for sending the campaign. (required).</param>
        /// <param name="rrule">RFC 5545 recurrence rule for recurring campaigns..</param>
        /// <param name="occurrenceSummary">Human-readable schedule description..</param>
        public ScheduledEmailCampaignDetails(int? id = default(int?), StatusEnum status = default(StatusEnum), int? emailSenderId = default(int?), DateTime? startAt = default(DateTime?), DateTime? endAt = default(DateTime?), DateTime? nextSendAt = default(DateTime?), UserPersonalInfo createdBy = default(UserPersonalInfo), DateTime? createdAt = default(DateTime?), DateTime? updatedAt = default(DateTime?), TypeEnum type = default(TypeEnum), string fromName = default(string), string fromEmail = default(string), string replyToEmail = default(string), string subject = default(string), string html = default(string), int? recipientsCount = default(int?), string sendingTimezone = default(string), string rrule = default(string), string occurrenceSummary = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            // to ensure "startAt" is required (not null)
            if (startAt == null)
            {
                throw new InvalidDataException("startAt is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.StartAt = startAt;
            }
            // to ensure "createdBy" is required (not null)
            if (createdBy == null)
            {
                throw new InvalidDataException("createdBy is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.CreatedBy = createdBy;
            }
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new InvalidDataException("createdAt is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.CreatedAt = createdAt;
            }
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new InvalidDataException("updatedAt is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.UpdatedAt = updatedAt;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "fromEmail" is required (not null)
            if (fromEmail == null)
            {
                throw new InvalidDataException("fromEmail is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.FromEmail = fromEmail;
            }
            // to ensure "replyToEmail" is required (not null)
            if (replyToEmail == null)
            {
                throw new InvalidDataException("replyToEmail is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.ReplyToEmail = replyToEmail;
            }
            // to ensure "subject" is required (not null)
            if (subject == null)
            {
                throw new InvalidDataException("subject is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.Subject = subject;
            }
            // to ensure "html" is required (not null)
            if (html == null)
            {
                throw new InvalidDataException("html is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.Html = html;
            }
            // to ensure "recipientsCount" is required (not null)
            if (recipientsCount == null)
            {
                throw new InvalidDataException("recipientsCount is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.RecipientsCount = recipientsCount;
            }
            // to ensure "sendingTimezone" is required (not null)
            if (sendingTimezone == null)
            {
                throw new InvalidDataException("sendingTimezone is a required property for ScheduledEmailCampaignDetails and cannot be null");
            }
            else
            {
                this.SendingTimezone = sendingTimezone;
            }
            this.EmailSenderId = emailSenderId;
            this.EndAt = endAt;
            this.NextSendAt = nextSendAt;
            this.FromName = fromName;
            this.Rrule = rrule;
            this.OccurrenceSummary = occurrenceSummary;
        }
        
        /// <summary>
        /// Unique scheduled campaign ID.
        /// </summary>
        /// <value>Unique scheduled campaign ID.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; set; }


        /// <summary>
        /// Email sender ID used for this campaign.
        /// </summary>
        /// <value>Email sender ID used for this campaign.</value>
        [DataMember(Name="emailSenderId", EmitDefaultValue=false)]
        public int? EmailSenderId { get; set; }

        /// <summary>
        /// Scheduled start timestamp (UTC).
        /// </summary>
        /// <value>Scheduled start timestamp (UTC).</value>
        [DataMember(Name="startAt", EmitDefaultValue=false)]
        public DateTime? StartAt { get; set; }

        /// <summary>
        /// End timestamp for recurring campaigns (UTC).
        /// </summary>
        /// <value>End timestamp for recurring campaigns (UTC).</value>
        [DataMember(Name="endAt", EmitDefaultValue=false)]
        public DateTime? EndAt { get; set; }

        /// <summary>
        /// Next scheduled send timestamp (UTC).
        /// </summary>
        /// <value>Next scheduled send timestamp (UTC).</value>
        [DataMember(Name="nextSendAt", EmitDefaultValue=false)]
        public DateTime? NextSendAt { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name="createdBy", EmitDefaultValue=false)]
        public UserPersonalInfo CreatedBy { get; set; }

        /// <summary>
        /// Campaign creation timestamp.
        /// </summary>
        /// <value>Campaign creation timestamp.</value>
        [DataMember(Name="createdAt", EmitDefaultValue=false)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Last update timestamp.
        /// </summary>
        /// <value>Last update timestamp.</value>
        [DataMember(Name="updatedAt", EmitDefaultValue=false)]
        public DateTime? UpdatedAt { get; set; }


        /// <summary>
        /// Sender name displayed in recipient&#39;s inbox.
        /// </summary>
        /// <value>Sender name displayed in recipient&#39;s inbox.</value>
        [DataMember(Name="fromName", EmitDefaultValue=false)]
        public string FromName { get; set; }

        /// <summary>
        /// Sender email address.
        /// </summary>
        /// <value>Sender email address.</value>
        [DataMember(Name="fromEmail", EmitDefaultValue=false)]
        public string FromEmail { get; set; }

        /// <summary>
        /// Reply-to email address.
        /// </summary>
        /// <value>Reply-to email address.</value>
        [DataMember(Name="replyToEmail", EmitDefaultValue=false)]
        public string ReplyToEmail { get; set; }

        /// <summary>
        /// Email subject line.
        /// </summary>
        /// <value>Email subject line.</value>
        [DataMember(Name="subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// HTML email content.
        /// </summary>
        /// <value>HTML email content.</value>
        [DataMember(Name="html", EmitDefaultValue=false)]
        public string Html { get; set; }

        /// <summary>
        /// Number of recipients for this campaign.
        /// </summary>
        /// <value>Number of recipients for this campaign.</value>
        [DataMember(Name="recipientsCount", EmitDefaultValue=false)]
        public int? RecipientsCount { get; set; }

        /// <summary>
        /// Timezone for sending the campaign.
        /// </summary>
        /// <value>Timezone for sending the campaign.</value>
        [DataMember(Name="sendingTimezone", EmitDefaultValue=false)]
        public string SendingTimezone { get; set; }

        /// <summary>
        /// RFC 5545 recurrence rule for recurring campaigns.
        /// </summary>
        /// <value>RFC 5545 recurrence rule for recurring campaigns.</value>
        [DataMember(Name="rrule", EmitDefaultValue=false)]
        public string Rrule { get; set; }

        /// <summary>
        /// Human-readable schedule description.
        /// </summary>
        /// <value>Human-readable schedule description.</value>
        [DataMember(Name="occurrenceSummary", EmitDefaultValue=false)]
        public string OccurrenceSummary { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduledEmailCampaignDetails {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  EmailSenderId: ").Append(EmailSenderId).Append("\n");
            sb.Append("  StartAt: ").Append(StartAt).Append("\n");
            sb.Append("  EndAt: ").Append(EndAt).Append("\n");
            sb.Append("  NextSendAt: ").Append(NextSendAt).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  FromEmail: ").Append(FromEmail).Append("\n");
            sb.Append("  ReplyToEmail: ").Append(ReplyToEmail).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Html: ").Append(Html).Append("\n");
            sb.Append("  RecipientsCount: ").Append(RecipientsCount).Append("\n");
            sb.Append("  SendingTimezone: ").Append(SendingTimezone).Append("\n");
            sb.Append("  Rrule: ").Append(Rrule).Append("\n");
            sb.Append("  OccurrenceSummary: ").Append(OccurrenceSummary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduledEmailCampaignDetails);
        }

        /// <summary>
        /// Returns true if ScheduledEmailCampaignDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduledEmailCampaignDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduledEmailCampaignDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.EmailSenderId == input.EmailSenderId ||
                    (this.EmailSenderId != null &&
                    this.EmailSenderId.Equals(input.EmailSenderId))
                ) && 
                (
                    this.StartAt == input.StartAt ||
                    (this.StartAt != null &&
                    this.StartAt.Equals(input.StartAt))
                ) && 
                (
                    this.EndAt == input.EndAt ||
                    (this.EndAt != null &&
                    this.EndAt.Equals(input.EndAt))
                ) && 
                (
                    this.NextSendAt == input.NextSendAt ||
                    (this.NextSendAt != null &&
                    this.NextSendAt.Equals(input.NextSendAt))
                ) && 
                (
                    this.CreatedBy == input.CreatedBy ||
                    (this.CreatedBy != null &&
                    this.CreatedBy.Equals(input.CreatedBy))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.FromName == input.FromName ||
                    (this.FromName != null &&
                    this.FromName.Equals(input.FromName))
                ) && 
                (
                    this.FromEmail == input.FromEmail ||
                    (this.FromEmail != null &&
                    this.FromEmail.Equals(input.FromEmail))
                ) && 
                (
                    this.ReplyToEmail == input.ReplyToEmail ||
                    (this.ReplyToEmail != null &&
                    this.ReplyToEmail.Equals(input.ReplyToEmail))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.Html == input.Html ||
                    (this.Html != null &&
                    this.Html.Equals(input.Html))
                ) && 
                (
                    this.RecipientsCount == input.RecipientsCount ||
                    (this.RecipientsCount != null &&
                    this.RecipientsCount.Equals(input.RecipientsCount))
                ) && 
                (
                    this.SendingTimezone == input.SendingTimezone ||
                    (this.SendingTimezone != null &&
                    this.SendingTimezone.Equals(input.SendingTimezone))
                ) && 
                (
                    this.Rrule == input.Rrule ||
                    (this.Rrule != null &&
                    this.Rrule.Equals(input.Rrule))
                ) && 
                (
                    this.OccurrenceSummary == input.OccurrenceSummary ||
                    (this.OccurrenceSummary != null &&
                    this.OccurrenceSummary.Equals(input.OccurrenceSummary))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.EmailSenderId != null)
                    hashCode = hashCode * 59 + this.EmailSenderId.GetHashCode();
                if (this.StartAt != null)
                    hashCode = hashCode * 59 + this.StartAt.GetHashCode();
                if (this.EndAt != null)
                    hashCode = hashCode * 59 + this.EndAt.GetHashCode();
                if (this.NextSendAt != null)
                    hashCode = hashCode * 59 + this.NextSendAt.GetHashCode();
                if (this.CreatedBy != null)
                    hashCode = hashCode * 59 + this.CreatedBy.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.UpdatedAt != null)
                    hashCode = hashCode * 59 + this.UpdatedAt.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.FromName != null)
                    hashCode = hashCode * 59 + this.FromName.GetHashCode();
                if (this.FromEmail != null)
                    hashCode = hashCode * 59 + this.FromEmail.GetHashCode();
                if (this.ReplyToEmail != null)
                    hashCode = hashCode * 59 + this.ReplyToEmail.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.Html != null)
                    hashCode = hashCode * 59 + this.Html.GetHashCode();
                if (this.RecipientsCount != null)
                    hashCode = hashCode * 59 + this.RecipientsCount.GetHashCode();
                if (this.SendingTimezone != null)
                    hashCode = hashCode * 59 + this.SendingTimezone.GetHashCode();
                if (this.Rrule != null)
                    hashCode = hashCode * 59 + this.Rrule.GetHashCode();
                if (this.OccurrenceSummary != null)
                    hashCode = hashCode * 59 + this.OccurrenceSummary.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
