/* 
 * Textmagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// ScheduleEmailCampaignResponse
    /// </summary>
    [DataContract]
    public partial class ScheduleEmailCampaignResponse :  IEquatable<ScheduleEmailCampaignResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleEmailCampaignResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleEmailCampaignResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleEmailCampaignResponse" /> class.
        /// </summary>
        /// <param name="campaign">campaign (required).</param>
        /// <param name="cost">Estimated cost for sending this campaign. (required).</param>
        public ScheduleEmailCampaignResponse(ScheduledEmailCampaignDetails campaign = default(ScheduledEmailCampaignDetails), float? cost = default(float?))
        {
            // to ensure "campaign" is required (not null)
            if (campaign == null)
            {
                throw new InvalidDataException("campaign is a required property for ScheduleEmailCampaignResponse and cannot be null");
            }
            else
            {
                this.Campaign = campaign;
            }
            // to ensure "cost" is required (not null)
            if (cost == null)
            {
                throw new InvalidDataException("cost is a required property for ScheduleEmailCampaignResponse and cannot be null");
            }
            else
            {
                this.Cost = cost;
            }
        }
        
        /// <summary>
        /// Gets or Sets Campaign
        /// </summary>
        [DataMember(Name="campaign", EmitDefaultValue=false)]
        public ScheduledEmailCampaignDetails Campaign { get; set; }

        /// <summary>
        /// Estimated cost for sending this campaign.
        /// </summary>
        /// <value>Estimated cost for sending this campaign.</value>
        [DataMember(Name="cost", EmitDefaultValue=false)]
        public float? Cost { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ScheduleEmailCampaignResponse {\n");
            sb.Append("  Campaign: ").Append(Campaign).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ScheduleEmailCampaignResponse);
        }

        /// <summary>
        /// Returns true if ScheduleEmailCampaignResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ScheduleEmailCampaignResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ScheduleEmailCampaignResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Campaign == input.Campaign ||
                    (this.Campaign != null &&
                    this.Campaign.Equals(input.Campaign))
                ) && 
                (
                    this.Cost == input.Cost ||
                    (this.Cost != null &&
                    this.Cost.Equals(input.Cost))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Campaign != null)
                    hashCode = hashCode * 59 + this.Campaign.GetHashCode();
                if (this.Cost != null)
                    hashCode = hashCode * 59 + this.Cost.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
