/* 
 * TextMagic API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TextMagicClient.Client.SwaggerDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// SenderSettingsItem
    /// </summary>
    [DataContract]
    public partial class SenderSettingsItem :  IEquatable<SenderSettingsItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SenderSettingsItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SenderSettingsItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SenderSettingsItem" /> class.
        /// </summary>
        /// <param name="country">Two-letter ISO country code of the recipient phone number.  (required).</param>
        /// <param name="phone">Phone enabled for sending to specified country (required).</param>
        public SenderSettingsItem(string country = default(string), string phone = default(string))
        {
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new InvalidDataException("country is a required property for SenderSettingsItem and cannot be null");
            }
            else
            {
                this.Country = country;
            }
            // to ensure "phone" is required (not null)
            if (phone == null)
            {
                throw new InvalidDataException("phone is a required property for SenderSettingsItem and cannot be null");
            }
            else
            {
                this.Phone = phone;
            }
        }
        
        /// <summary>
        /// Two-letter ISO country code of the recipient phone number. 
        /// </summary>
        /// <value>Two-letter ISO country code of the recipient phone number. </value>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// Phone enabled for sending to specified country
        /// </summary>
        /// <value>Phone enabled for sending to specified country</value>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SenderSettingsItem {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SenderSettingsItem);
        }

        /// <summary>
        /// Returns true if SenderSettingsItem instances are equal
        /// </summary>
        /// <param name="input">Instance of SenderSettingsItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SenderSettingsItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
