/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// SenderSettingsItem
    /// </summary>
    [DataContract(Name = "SenderSettingsItem")]
    public partial class SenderSettingsItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SenderSettingsItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SenderSettingsItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SenderSettingsItem" /> class.
        /// </summary>
        /// <param name="country">The 2-letter ISO country code of the recipient&#39;s phone number.  (required).</param>
        /// <param name="phone">Phone enabled for sending to a specified country. (required).</param>
        public SenderSettingsItem(string country = default, string phone = default)
        {
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for SenderSettingsItem and cannot be null");
            }
            this.Country = country;
            // to ensure "phone" is required (not null)
            if (phone == null)
            {
                throw new ArgumentNullException("phone is a required property for SenderSettingsItem and cannot be null");
            }
            this.Phone = phone;
        }

        /// <summary>
        /// The 2-letter ISO country code of the recipient&#39;s phone number. 
        /// </summary>
        /// <value>The 2-letter ISO country code of the recipient&#39;s phone number. </value>
        /*
        <example>US</example>
        */
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Phone enabled for sending to a specified country.
        /// </summary>
        /// <value>Phone enabled for sending to a specified country.</value>
        /*
        <example>+447937946700</example>
        */
        [DataMember(Name = "phone", IsRequired = true, EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SenderSettingsItem {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
