/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// SendMessageRequest
    /// </summary>
    [DataContract(Name = "sendMessage_request")]
    public partial class SendMessageRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendMessageRequest" /> class.
        /// </summary>
        /// <param name="text">Message text. Required if the **template_id** is not set..</param>
        /// <param name="templateId">Template used instead of message text. Required if the **text** is not set..</param>
        /// <param name="sendingTime">DEPRECATED, consider using sendingDateTime and sendingTimezone parameters instead: Optional (required with rrule set). Message sending time in unix timestamp format. Default is now..</param>
        /// <param name="sendingDateTime">Sending time in Y-m-d H:i:s format (e.g. 2022-05-27 13:05:10). This time is relative to **sendingTimezone**. Note: for correct operation, the value of seconds must not be less than 10..</param>
        /// <param name="sendingTimezone">ID or ISO-name of timezone used for sending when sendingDateTime parameter is set. E.g. if you specify sendingDateTime &#x3D; \\\&quot;2016-05-27 13:02:33\\\&quot; and sendingTimezone &#x3D; \\\&quot;America/Buenos_Aires\\\&quot;, your message will be sent at May 27, 2016 13:02:33 Buenos Aires time, or 16:02:33 UTC. Default is account timezone..</param>
        /// <param name="contacts">Comma separated array of contact resources id message will be sent to..</param>
        /// <param name="lists">Comma separated array of list resources id message will be sent to..</param>
        /// <param name="phones">Comma separated array of E.164 phone numbers message will be sent to..</param>
        /// <param name="cutExtra">Should sending method cut extra characters which not fit supplied partsCount or return 400 Bad request response instead. (default to false).</param>
        /// <param name="partsCount">Maximum message parts count (Textmagic allows sending 1 to 6 message parts)..</param>
        /// <param name="referenceId">Custom message reference id which can be used in your application infrastructure..</param>
        /// <param name="from">One of allowed Sender ID (phone number or alphanumeric sender ID). If specified Sender ID is not allowed for some destinations, a fallback default Sender ID will be used to ensure delivery. See [Get timezones](https://docs.textmagic.com/#tag/Sender-IDs)..</param>
        /// <param name="rrule">iCal RRULE parameter to create recurrent scheduled messages. When used, sendingTime is mandatory as start point of sending. See https://www.textmagic.com/free-tools/rrule-generator for format details..</param>
        /// <param name="createChat">Should sending method try to create new Chat (if not exist) with specified recipients? (default to false).</param>
        /// <param name="tts">Send a Text-to-Speech message. (default to false).</param>
        /// <param name="local">Treat phone numbers passed in the \\&#39;phones\\&#39; field as local. (default to false).</param>
        /// <param name="localCountry">The 2-letter ISO country code for local phone numbers, used when \\&#39;local\\&#39; is set to true. Default is the account country..</param>
        /// <param name="destination">Messsage destination type allowed [mms, tts]..</param>
        /// <param name="resources">File name from mms attachment response (named as resource).</param>
        public SendMessageRequest(string text = default, int templateId = default, int sendingTime = default, string sendingDateTime = default, string sendingTimezone = default, string contacts = default, string lists = default, string phones = default, bool cutExtra = false, int partsCount = default, int referenceId = default, string from = default, string rrule = default, bool createChat = false, bool tts = false, bool local = false, string localCountry = default, string destination = default, string resources = default)
        {
            this.Text = text;
            this.TemplateId = templateId;
            this.SendingTime = sendingTime;
            this.SendingDateTime = sendingDateTime;
            this.SendingTimezone = sendingTimezone;
            this.Contacts = contacts;
            this.Lists = lists;
            this.Phones = phones;
            this.CutExtra = cutExtra;
            this.PartsCount = partsCount;
            this.ReferenceId = referenceId;
            this.From = from;
            this.Rrule = rrule;
            this.CreateChat = createChat;
            this.Tts = tts;
            this.Local = local;
            this.LocalCountry = localCountry;
            this.Destination = destination;
            this.Resources = resources;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Message text. Required if the **template_id** is not set.
        /// </summary>
        /// <value>Message text. Required if the **template_id** is not set.</value>
        /*
        <example>Hello, how are you?</example>
        */
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Template used instead of message text. Required if the **text** is not set.
        /// </summary>
        /// <value>Template used instead of message text. Required if the **text** is not set.</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "templateId", EmitDefaultValue = false)]
        public int TemplateId { get; set; }

        /// <summary>
        /// DEPRECATED, consider using sendingDateTime and sendingTimezone parameters instead: Optional (required with rrule set). Message sending time in unix timestamp format. Default is now.
        /// </summary>
        /// <value>DEPRECATED, consider using sendingDateTime and sendingTimezone parameters instead: Optional (required with rrule set). Message sending time in unix timestamp format. Default is now.</value>
        /*
        <example>1565606455</example>
        */
        [DataMember(Name = "sendingTime", EmitDefaultValue = false)]
        public int SendingTime { get; set; }

        /// <summary>
        /// Sending time in Y-m-d H:i:s format (e.g. 2022-05-27 13:05:10). This time is relative to **sendingTimezone**. Note: for correct operation, the value of seconds must not be less than 10.
        /// </summary>
        /// <value>Sending time in Y-m-d H:i:s format (e.g. 2022-05-27 13:05:10). This time is relative to **sendingTimezone**. Note: for correct operation, the value of seconds must not be less than 10.</value>
        /*
        <example>2020-05-27 13:02:33</example>
        */
        [DataMember(Name = "sendingDateTime", EmitDefaultValue = false)]
        public string SendingDateTime { get; set; }

        /// <summary>
        /// ID or ISO-name of timezone used for sending when sendingDateTime parameter is set. E.g. if you specify sendingDateTime &#x3D; \\\&quot;2016-05-27 13:02:33\\\&quot; and sendingTimezone &#x3D; \\\&quot;America/Buenos_Aires\\\&quot;, your message will be sent at May 27, 2016 13:02:33 Buenos Aires time, or 16:02:33 UTC. Default is account timezone.
        /// </summary>
        /// <value>ID or ISO-name of timezone used for sending when sendingDateTime parameter is set. E.g. if you specify sendingDateTime &#x3D; \\\&quot;2016-05-27 13:02:33\\\&quot; and sendingTimezone &#x3D; \\\&quot;America/Buenos_Aires\\\&quot;, your message will be sent at May 27, 2016 13:02:33 Buenos Aires time, or 16:02:33 UTC. Default is account timezone.</value>
        /*
        <example>America/Buenos_Aires</example>
        */
        [DataMember(Name = "sendingTimezone", EmitDefaultValue = false)]
        public string SendingTimezone { get; set; }

        /// <summary>
        /// Comma separated array of contact resources id message will be sent to.
        /// </summary>
        /// <value>Comma separated array of contact resources id message will be sent to.</value>
        /*
        <example>1,2,3,4</example>
        */
        [DataMember(Name = "contacts", EmitDefaultValue = false)]
        public string Contacts { get; set; }

        /// <summary>
        /// Comma separated array of list resources id message will be sent to.
        /// </summary>
        /// <value>Comma separated array of list resources id message will be sent to.</value>
        /*
        <example>1,2,3,4</example>
        */
        [DataMember(Name = "lists", EmitDefaultValue = false)]
        public string Lists { get; set; }

        /// <summary>
        /// Comma separated array of E.164 phone numbers message will be sent to.
        /// </summary>
        /// <value>Comma separated array of E.164 phone numbers message will be sent to.</value>
        /*
        <example>447860021130,447860021131</example>
        */
        [DataMember(Name = "phones", EmitDefaultValue = false)]
        public string Phones { get; set; }

        /// <summary>
        /// Should sending method cut extra characters which not fit supplied partsCount or return 400 Bad request response instead.
        /// </summary>
        /// <value>Should sending method cut extra characters which not fit supplied partsCount or return 400 Bad request response instead.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "cutExtra", EmitDefaultValue = true)]
        public bool CutExtra { get; set; }

        /// <summary>
        /// Maximum message parts count (Textmagic allows sending 1 to 6 message parts).
        /// </summary>
        /// <value>Maximum message parts count (Textmagic allows sending 1 to 6 message parts).</value>
        /*
        <example>6</example>
        */
        [DataMember(Name = "partsCount", EmitDefaultValue = false)]
        public int PartsCount { get; set; }

        /// <summary>
        /// Custom message reference id which can be used in your application infrastructure.
        /// </summary>
        /// <value>Custom message reference id which can be used in your application infrastructure.</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "referenceId", EmitDefaultValue = false)]
        public int ReferenceId { get; set; }

        /// <summary>
        /// One of allowed Sender ID (phone number or alphanumeric sender ID). If specified Sender ID is not allowed for some destinations, a fallback default Sender ID will be used to ensure delivery. See [Get timezones](https://docs.textmagic.com/#tag/Sender-IDs).
        /// </summary>
        /// <value>One of allowed Sender ID (phone number or alphanumeric sender ID). If specified Sender ID is not allowed for some destinations, a fallback default Sender ID will be used to ensure delivery. See [Get timezones](https://docs.textmagic.com/#tag/Sender-IDs).</value>
        /*
        <example>Test sender id</example>
        */
        [DataMember(Name = "from", EmitDefaultValue = false)]
        public string From { get; set; }

        /// <summary>
        /// iCal RRULE parameter to create recurrent scheduled messages. When used, sendingTime is mandatory as start point of sending. See https://www.textmagic.com/free-tools/rrule-generator for format details.
        /// </summary>
        /// <value>iCal RRULE parameter to create recurrent scheduled messages. When used, sendingTime is mandatory as start point of sending. See https://www.textmagic.com/free-tools/rrule-generator for format details.</value>
        /*
        <example>FREQ&#x3D;YEARLY;BYMONTH&#x3D;1;BYMONTHDAY&#x3D;1;COUNT&#x3D;1</example>
        */
        [DataMember(Name = "rrule", EmitDefaultValue = false)]
        public string Rrule { get; set; }

        /// <summary>
        /// Should sending method try to create new Chat (if not exist) with specified recipients?
        /// </summary>
        /// <value>Should sending method try to create new Chat (if not exist) with specified recipients?</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "createChat", EmitDefaultValue = true)]
        public bool CreateChat { get; set; }

        /// <summary>
        /// Send a Text-to-Speech message.
        /// </summary>
        /// <value>Send a Text-to-Speech message.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "tts", EmitDefaultValue = true)]
        public bool Tts { get; set; }

        /// <summary>
        /// Treat phone numbers passed in the \\&#39;phones\\&#39; field as local.
        /// </summary>
        /// <value>Treat phone numbers passed in the \\&#39;phones\\&#39; field as local.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "local", EmitDefaultValue = true)]
        public bool Local { get; set; }

        /// <summary>
        /// The 2-letter ISO country code for local phone numbers, used when \\&#39;local\\&#39; is set to true. Default is the account country.
        /// </summary>
        /// <value>The 2-letter ISO country code for local phone numbers, used when \\&#39;local\\&#39; is set to true. Default is the account country.</value>
        /*
        <example>US</example>
        */
        [DataMember(Name = "localCountry", EmitDefaultValue = false)]
        public string LocalCountry { get; set; }

        /// <summary>
        /// Messsage destination type allowed [mms, tts].
        /// </summary>
        /// <value>Messsage destination type allowed [mms, tts].</value>
        /*
        <example>mms</example>
        */
        [DataMember(Name = "destination", EmitDefaultValue = false)]
        public string Destination { get; set; }

        /// <summary>
        /// File name from mms attachment response (named as resource)
        /// </summary>
        /// <value>File name from mms attachment response (named as resource)</value>
        /*
        <example>tmauKcSmwflB77kLQ15904023426649.jpg</example>
        */
        [DataMember(Name = "resources", EmitDefaultValue = false)]
        public string Resources { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendMessageRequest {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  SendingTime: ").Append(SendingTime).Append("\n");
            sb.Append("  SendingDateTime: ").Append(SendingDateTime).Append("\n");
            sb.Append("  SendingTimezone: ").Append(SendingTimezone).Append("\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  Lists: ").Append(Lists).Append("\n");
            sb.Append("  Phones: ").Append(Phones).Append("\n");
            sb.Append("  CutExtra: ").Append(CutExtra).Append("\n");
            sb.Append("  PartsCount: ").Append(PartsCount).Append("\n");
            sb.Append("  ReferenceId: ").Append(ReferenceId).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  Rrule: ").Append(Rrule).Append("\n");
            sb.Append("  CreateChat: ").Append(CreateChat).Append("\n");
            sb.Append("  Tts: ").Append(Tts).Append("\n");
            sb.Append("  Local: ").Append(Local).Append("\n");
            sb.Append("  LocalCountry: ").Append(LocalCountry).Append("\n");
            sb.Append("  Destination: ").Append(Destination).Append("\n");
            sb.Append("  Resources: ").Append(Resources).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
