/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// UnsubscribedContact
    /// </summary>
    [DataContract(Name = "UnsubscribedContact")]
    public partial class UnsubscribedContact : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsubscribedContact" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UnsubscribedContact() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsubscribedContact" /> class.
        /// </summary>
        /// <param name="id">Unsubscribed contact ID. (required).</param>
        /// <param name="phone">Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164). (required).</param>
        /// <param name="unsubscribeTime">Time when contact was opted-out. (required).</param>
        /// <param name="firstName">Unsubscribed contact first name. (required).</param>
        /// <param name="lastName">Unsubscribed contact last name. (required).</param>
        public UnsubscribedContact(int id = default, string phone = default, DateTime unsubscribeTime = default, string firstName = default, string lastName = default)
        {
            this.Id = id;
            // to ensure "phone" is required (not null)
            if (phone == null)
            {
                throw new ArgumentNullException("phone is a required property for UnsubscribedContact and cannot be null");
            }
            this.Phone = phone;
            this.UnsubscribeTime = unsubscribeTime;
            // to ensure "firstName" is required (not null)
            if (firstName == null)
            {
                throw new ArgumentNullException("firstName is a required property for UnsubscribedContact and cannot be null");
            }
            this.FirstName = firstName;
            // to ensure "lastName" is required (not null)
            if (lastName == null)
            {
                throw new ArgumentNullException("lastName is a required property for UnsubscribedContact and cannot be null");
            }
            this.LastName = lastName;
        }

        /// <summary>
        /// Unsubscribed contact ID.
        /// </summary>
        /// <value>Unsubscribed contact ID.</value>
        /*
        <example>27074</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).
        /// </summary>
        /// <value>Phone number in [E.164 format](https://en.wikipedia.org/wiki/E.164).</value>
        /*
        <example>447860021130</example>
        */
        [DataMember(Name = "phone", IsRequired = true, EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Time when contact was opted-out.
        /// </summary>
        /// <value>Time when contact was opted-out.</value>
        [DataMember(Name = "unsubscribeTime", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UnsubscribeTime { get; set; }

        /// <summary>
        /// Unsubscribed contact first name.
        /// </summary>
        /// <value>Unsubscribed contact first name.</value>
        /*
        <example>Charles</example>
        */
        [DataMember(Name = "firstName", IsRequired = true, EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Unsubscribed contact last name.
        /// </summary>
        /// <value>Unsubscribed contact last name.</value>
        /*
        <example>Conway</example>
        */
        [DataMember(Name = "lastName", IsRequired = true, EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnsubscribedContact {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  UnsubscribeTime: ").Append(UnsubscribeTime).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
