/*
 * Textmagic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TextMagicClient.Client.OpenAPIDateConverter;

namespace TextMagicClient.Model
{
    /// <summary>
    /// UpdateInboundMessagesNotificationSettingsRequest
    /// </summary>
    [DataContract(Name = "updateInboundMessagesNotificationSettings_request")]
    public partial class UpdateInboundMessagesNotificationSettingsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateInboundMessagesNotificationSettingsRequest" /> class.
        /// </summary>
        /// <param name="inboundMessageNotification">Should user receive notification about new incoming messages..</param>
        /// <param name="includeSmsHistory">Include SMS history into notification Email..</param>
        /// <param name="sendInHtmlFormat">Send Email notification in HTML format..</param>
        /// <param name="alertEmail1">New message notification email 2..</param>
        /// <param name="alertEmail2">New message notification email 2..</param>
        /// <param name="alertEmail3">New message notification email 3..</param>
        public UpdateInboundMessagesNotificationSettingsRequest(bool inboundMessageNotification = default, bool includeSmsHistory = default, bool sendInHtmlFormat = default, string alertEmail1 = default, string alertEmail2 = default, string alertEmail3 = default)
        {
            this.InboundMessageNotification = inboundMessageNotification;
            this.IncludeSmsHistory = includeSmsHistory;
            this.SendInHtmlFormat = sendInHtmlFormat;
            this.AlertEmail1 = alertEmail1;
            this.AlertEmail2 = alertEmail2;
            this.AlertEmail3 = alertEmail3;
        }

        /// <summary>
        /// Should user receive notification about new incoming messages.
        /// </summary>
        /// <value>Should user receive notification about new incoming messages.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "inboundMessageNotification", EmitDefaultValue = true)]
        public bool InboundMessageNotification { get; set; }

        /// <summary>
        /// Include SMS history into notification Email.
        /// </summary>
        /// <value>Include SMS history into notification Email.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "includeSmsHistory", EmitDefaultValue = true)]
        public bool IncludeSmsHistory { get; set; }

        /// <summary>
        /// Send Email notification in HTML format.
        /// </summary>
        /// <value>Send Email notification in HTML format.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "sendInHtmlFormat", EmitDefaultValue = true)]
        public bool SendInHtmlFormat { get; set; }

        /// <summary>
        /// New message notification email 2.
        /// </summary>
        /// <value>New message notification email 2.</value>
        /*
        <example>test@test.com</example>
        */
        [DataMember(Name = "alertEmail1", EmitDefaultValue = false)]
        public string AlertEmail1 { get; set; }

        /// <summary>
        /// New message notification email 2.
        /// </summary>
        /// <value>New message notification email 2.</value>
        /*
        <example>test@test.com</example>
        */
        [DataMember(Name = "alertEmail2", EmitDefaultValue = false)]
        public string AlertEmail2 { get; set; }

        /// <summary>
        /// New message notification email 3.
        /// </summary>
        /// <value>New message notification email 3.</value>
        /*
        <example>test@test.com</example>
        */
        [DataMember(Name = "alertEmail3", EmitDefaultValue = false)]
        public string AlertEmail3 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateInboundMessagesNotificationSettingsRequest {\n");
            sb.Append("  InboundMessageNotification: ").Append(InboundMessageNotification).Append("\n");
            sb.Append("  IncludeSmsHistory: ").Append(IncludeSmsHistory).Append("\n");
            sb.Append("  SendInHtmlFormat: ").Append(SendInHtmlFormat).Append("\n");
            sb.Append("  AlertEmail1: ").Append(AlertEmail1).Append("\n");
            sb.Append("  AlertEmail2: ").Append(AlertEmail2).Append("\n");
            sb.Append("  AlertEmail3: ").Append(AlertEmail3).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
